### ISSUE TITLE
add support deriving syntax extensions

### ISSUE THREAD

**Issue by struktured** [the-lambda-church/merlin#168]
The fairly popular "deriving" extensions (https://github.com/jaked/deriving) currently show compiler errors. 

For example :

```
open Deriving_Show

type foo = int deriving (Show)
(* ^^ above line shows syntax error *)
```

Besides that, merlin is great! Please support deriving extensions in the next merlin release if possible!

Cheers,
Carmelo

**Comment by trefis** [comment]
Hm, I never took care of this apparently.
I guess I can close as deriving is a now PPX extension.
