### ISSUE TITLE
Better errors when skipping bad definitions

### ISSUE THREAD

**Issue by roshanjames** [the-lambda-church/merlin#197]
If I have:

```ocaml
module M = ...some valid definition...

module M = F(X)

let _ = M 
```

Lets assume that [X] does not satisfy the signature that [F]
expects, i.e. the functor application is broken. When one asks
for the type of [M] in the last line, the type of the original
definition is reported.

This is very confusing. Ideally, merlin should report some error
saying that an intermediate definition of [M] was malformed,
instead of silently reporting the wrong type.

Value definitions seem to work a bit differently.  If I have the
followng snippet:

```ocaml
let f = 10 

let f = () ()

let _ = f 
```

and we ask for the type of [f] we see ['a]. In this case merlin
remembers the fact that it saw an [f] with a bad type. 

But if we just had a syntax error: 

```ocaml
let f = 10 

let f = (

let _ = f
```

we now see [int].

Its a bit confusing that this happens for the same reasons. If
the two definitions of [f] are pretty far apart this gets really
hard to track down.

Like with modules, even though the second definition of [f] is
malformed, it would be nice to know that any later reference is
not to the original [f] but to some unknown thing.

**Comment by trefis** [comment]
Hi!

This thread is pretty old, and the example which motivated the issue

```ocaml
module M = ...
module M = F(X (* erroneous *))
let _ = M
```
is nowadays handled as expected (`M` on the last line has the return type of `F`).

Things are overall much better (more precise type recovery, much better syntax recovery), though they can still be somewhat improved.
But I think this issue can safely be closed.

> Correct me if I am wrong, but didn't merlin start as a
modified ocaml top-level/REPL with the evaluator culled out?

Nope :)

**Comment by def-lkb** [comment]
>> Correct me if I am wrong, but didn't merlin start as a
>> modified ocaml top-level/REPL with the evaluator culled out?
>
> Nope :)

Well, for a few days in late december 2012, it was :).
