### ISSUE TITLE
PPX support

### ISSUE THREAD

**Issue by whitequark** [the-lambda-church/merlin#226]
Naturally, I only use 4.02, as most of my work includes usage of extension points.

**Comment by edwintorok** [comment]
I was pleasantly surprised to find out that with merlin 2.1.2 some ppx extensions seem to be working by just adding the relevant ocamlfind package (for example `cconv.ppx`). 
Is this feature still experimental or is it stable enough to be mentioned in the README?

**Comment by whitequark** [comment]
Should be stable as it uses the same logic as toplevel.

**Comment by hcarty** [comment]
Composing PPX extensions seems to still have issues.  The example in ppx_import's README mixing ppx_import and ppx_deriving (https://github.com/whitequark/ppx_import#combining-with-deriving) does not work in vim even if I manually `:Use ppx_import` and then `:Use ppx_deriving.std`.  The same works from vanilla `ocaml`, `utop` or normal compilation.

**Comment by def-lkb** [comment]
merlin applies ppx ordered by their name… I don't know what would be the best way, probably by order of appearance but then there is some ambiguity when mixing ppx from .merlin and from :Use.

Also, it is still unclear to me what is the correct way to specify ppx options.

**Comment by gasche** [comment]
A cascading model would suggest that `.merlin` preprocessors be applied prior to `:Use` preprocessors.

**Comment by def-lkb** [comment]
@hcarty : should be fixed in latest git.

**Comment by hcarty** [comment]
master works for me under 4.02.1 @def-lkb.  Thank you!
