### ISSUE TITLE
support the cstruct syntax extension

### ISSUE THREAD

**Issue by samoht** [the-lambda-church/merlin#252]
Example:
```
 cstruct pseudo_header {
    uint32_t src;
    uint32_t dst;
    uint8_t res;
    uint8_t proto;
    uint16_t len
  } as big_endian
```

**Comment by trefis** [comment]
Is this still relevant?
Did cstruct switch to PPX or plan to do it in the near future?

**Comment by haesbaert** [comment]
cstruct is using ppx already, would be great to have support in it.

**Comment by let-def** [comment]
Cstruct switched to PPX, `.merlin` directive:
`PKG cstruct.ppx`
