### ISSUE TITLE
Can merlin highlight function names of curried expressions?

### ISSUE THREAD

**Issue by unhammer** [the-lambda-church/merlin#305]
Forgetting to include some parameter can at times lead to  confusing debugging, like if I started out doing `|> List.map (fun e -> …)` and then changed it to `let l = … in List.map (fun e-> …)` but forgot to add the `l` at the end, and the expression is a curried function instead of a list. (This gets worse when the function expects lots of optional function-arguments and  trying `merlin-type-enclosing` on it gives halv a screenful of arrows and parens.)

Since this is not an error in itself, but is still more of an exception than the rule, how about e.g. underlining (or at least allowing the user to set some special font-face) for the `List.map` part when it doesn't have all its arguments filled? If I know I want it curried, I ignore the underline, but if not it's a good hint that this is where the error is (and faster than manually checking lots of signatures).

**Comment by trefis** [comment]
This feels like something I would find extremely annoying to have, also it is annoying to implement.
I would suggest enabling the appropriate warning (`FLG -w +5` in your .merlin) but that doesn't really catch anything...
I guess what you really wants are better error messages from caml, you can either hope that Arthur Chargéraud's patch gets merged ( https://github.com/ocaml/ocaml/pull/102 ) or you can start adding more type annotations to your programs :)
