### ISSUE TITLE
Error when getting type of identifier.

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#334]
Error getting the type of an identfier:

https://www.evernote.com/shard/s417/sh/34adc791-6bed-475d-afc6-fc4b957c6327/871c24df764eaf1c5afbefaae89a4cb9

Here's the file:

https://github.com/rgrinberg/opam-publish/blob/master/src/opam_publish.ml#L100

The identifier is `pull_url`.

Here's my `.merlin`:

```
PKG opam-lib.client
PKG github
PKG cmdliner
S src
B _build/src/**
```

(you might need the master version of opam to reproduce this but I'm not sure)

**Comment by def-lkb** [comment]
It's vim bug [ftp://ftp.vim.org/pub/vim/patches/7.4/7.4.424]().
So you will need at least version 7.4.424 to get colored types.

**Comment by struktured** [comment]
I applied that patch to the vim source code I use, resolved it. Thanks!
