### ISSUE TITLE
Syntax highlighting support for code completion results (vim)

### ISSUE THREAD

**Issue by struktured** [the-lambda-church/merlin#340]
In the latest iteration of the merlin vim plugin, the "type of" (\t) command shows a syntax highlighted version of the type signature, which is quite nice. 

Is it possible to have a similar highlighting strategy for the code completion results (the ones shown via ctrl-x-o) ?

**Comment by def-lkb** [comment]
While it was possible to get colored types thanks to a great hack by @art-w, I don't think similar feature can be brought to completion window.
Most vim behaviors are hardcoded and the implementation is unbelievably unreliable.
