### ISSUE TITLE
Makefile install targets

### ISSUE THREAD

**Issue by holomorph** [the-lambda-church/merlin#344]
The vim install target does not use DESTDIR, which is troublesome.

Also, since the emacs files are installed to the usual site location, shouldn't vim files be installed to `SHAREDIR/vim/vimfiles`?

Since the vim stuff looks separated from the rest in the configure script and makefiles, I'm not sure how to go about fixing it myself.

**Comment by holomorph** [comment]
> Also, since the emacs files are installed to the usual site location, shouldn't vim files be installed to SHAREDIR/vim/vimfiles?

Nevermind, I see a good reason why: the python dependency

**Comment by def-lkb** [comment]
Yes. I'll close for now. Feel free to ping/reopen if you have any idea how to improve this situation.

**Comment by holomorph** [comment]
If just prepending $(DESTDIR) to the directories in the vim-install target is fine, I'd be happy to make a patch for that.
