### ISSUE TITLE
merlin stuck in a syntax error that is not a syntax error

### ISSUE THREAD

**Issue by smondet** [the-lambda-church/merlin#345]
I get the problem with this [file](https://github.com/hammerlab/ketrew/blob/automat/src/lib/ketrew_engine.ml) and other ones too.

- getting the type or locating values that come from the same file do not work, while values from other modules work.
- the code compiles, there is no syntax extension / no extension point
- `merlin-error-prev` finds an error anyways:

At line 128:

```
  Log.(s "Going through not implemented stuff: " % s msg @ verbose);
```

at the `%` (it's the first one in that file) the error is: ``Syntax error inside `let' after unclosed (, expecting `#' or `.' ``

then there is also a warning at that line (on the ``s "Going through not implemented stuff: "`` part):
`` Warning 10: this expression should have type unit. ``

I am using merlin's master branch (just re-pulled a few minutes ago).

**Comment by def-lkb** [comment]
(Seems) Fixed.
