### ISSUE TITLE
Please document the new functionality in the Vim plugin

### ISSUE THREAD

**Issue by edwintorok** [the-lambda-church/merlin#346]
`:Destruct` 
> The introduction of a "destruct" command for automatic match pattern
generation, as demonstrated on :

`:Outline` and `:ILocate`
> ctrlp bindings for outline and locate

I figured out how destruct works from the video (nice!), and outline seems to work.
But I can't figure out what `:ILocate` is for, I get ` == NO ENTRIES ==` when cursor is on an entry where `:Locate` itself would work.

**Comment by trefis** [comment]
The I in ILocate stands for interactive, the idea is that when you start entering some input it will display all the things in the environment which name contains your input as a prefix.
That's the idea. It does not work here for me either, to be honest I had completely forgotten about that function and I don't remember if I ever got it to work properly (most probable answer: no). I will experiment with it in the next few days, to see if I can make it work properly.

I'll also add some documentation.

**Comment by edwintorok** [comment]
Did a quick test in my project and it worked (typed Xml.tag and it took me to CodedIO.Xml.tag, or L.map and it showed List.map but obviously without jumping there).

So `:ILocate` is similar to omnicompletion but interactively updated, without the type info and instead of inserting the completion it takes you to the definition.
I like the idea, maybe you can take it further and create an `:IDoc` command that shows the type info, and ocamldoc in preview: would be quite useful for browsing module interfaces/documentation.

Regarding  the initial 'NO ENTRIES' message: it is confusing and it doesn't make me think that typing something will find more entries because ctrl+p usually displays everything and then narrows it down with a filter.
If you have some control over that message could you add a hint that typing will reveal more entries?

**Comment by trefis** [comment]
It took a while, but it is done.
I fixed `:ILocate`, changed the initial message and updated the documentation.
