### ISSUE TITLE
Rename doesn't work with ppx

### ISSUE THREAD

**Issue by Emm** [the-lambda-church/merlin#347]
STR:

Given a project using lwt.ppx, try to rename `foo` in the program:

```ocaml
let _ = Lwt_main.run (
  let%lwt foo = Lwt.return "foo" in
  let%lwt foobar = Lwt.return (foo ^ "bar") in
  Lwt.return ()
)
```

And the `IncrementalRename()` function complains of "No occurrences found!".  And though I haven't managed to create a small reproduction case for this, the incremental rename function occasionally selects the "let " part of a normal variable instead of the variable itself, and then prefixes every single character since the beginning the file with "let $newvariablename". I haven't observed this in non-PPX viles.

**Comment by def-lkb** [comment]
Fixed in browse-node-no-loc branch (locations were computed erroneously -- browse-node introduced "location normalization", and browse-node-no-loc extends the sceme to approximate best locations).
