### ISSUE TITLE
badly formed mli make emacs freeze

### ISSUE THREAD

**Issue by pirbo** [the-lambda-church/merlin#348]
Using merlin 2.1.1 installed by opam, in emacs, when I write in a .mli ```val x : int -> (int, int) -> int``` instead of ```val x : int -> (int * int) -> int``` (which is sadly a mistake I often do), the next save (or M-x merlin-reload) will make my emacs 24.4 freeze 99% of the time.

I deterministically (3 time in a row) reproduce the bug by
- pasting ```val x : int -> (int, int) -> int``` in a empty .mli file
- save (this one works)
- add a line ```val y : unit```
- save

the mini buffers stay frozen saying ```Wrote /Users/pirbo/toto.mli``` always but once where it said
```Command (tell start at ((assoc) (line . 2) (col . 0))) failed with error TODO```. Maybe, this might help ...

**Comment by def-lkb** [comment]
Thanks for the clean bug report.
Fixed two bugs:
- error handling code freezing emacs,
- implemented fallback for invalid types (yours is now parsed as `int -> _ -> int`)

You should have the proper behavior in latest master. I'm closing for now, reopen if this still causes you problem.
