### ISSUE TITLE
Vim: Use tagstack for :Locate command?

### ISSUE THREAD

**Issue by edgemaster** [the-lambda-church/merlin#349]
I'm browsing through a new, large OCaml codebase and finding that I'm using :Locate a lot, and needing to jump back to the previous location.
The Vim tagstack bindings of CTRL-] and CTRL-T would be very useful for this.

**Comment by trefis** [comment]
`Locate` already interacts with the jumplist, see `:h CTRL-O`.

**Comment by edgemaster** [comment]
Closed: User error :)

**Comment by trefis** [comment]
No worries; we should probably mention it in the documentation...
