### ISSUE TITLE
Typo in MerlinSearchOccur(r)ences

### ISSUE THREAD

**Issue by talex5** [the-lambda-church/merlin#350]
`merlin.vim` has:

    nmap <silent><buffer> <Plug>(MerlinSearchOccurencesForward) ...
    nmap <silent><buffer> <Plug>(MerlinSearchOccurrencesBackward) ...

Note that the spelling of `Occurences` varies, and this is not consistent with the documentation.

**Comment by def-lkb** [comment]
Exact, thanks :) (R in occurrrrrrences have been a recurrrrent problem).
