### ISSUE TITLE
Incompatibility with fieldslib

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#351]
Opening the following file in merlin will wrongly report an error in syntastic: `Error: Unbound module Field`

https://github.com/mirage/ocaml-cohttp/blob/master/lib/response.ml#L26

You can clone the whole repo https://github.com/mirage/ocaml-cohttp which has the appropriate .merlin file to reproduce this.

**Comment by trefis** [comment]
I pushed a fix on master. :)
