### ISSUE TITLE
Vim Plugin: different default highlight color.

### ISSUE THREAD

**Issue by jordwalke** [the-lambda-church/merlin#353]
It would be nice if we reused a highlight color that was already in the colorscheme. The current default clashes with many colorschemes. I suppose this one is easy enough for me to send a pull request for, just curious if anyone would object to doing:

      hi def link EnclosingExpr IncSearch

`IncSearch` is likely already configured to be visible on the background color, and it's usually only visible for a short while during typing of a search pattern (which makes it a better for linking to than `Search` - which would cause search terms to be confused with the `merlin` highlight region).

**Comment by jordwalke** [comment]
Obviously super low priority!

**Comment by trefis** [comment]
Good call.
