### ISSUE TITLE
Merlin doesn't treat duplicate modules as error

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#354]
Given the following file:

```ocaml
module X = struct end
module X = struct end
```

Merlin (using syntastic) will not signal of any error. However, ocamlc will complain:

```
Error: Multiple definition of the module name X. Names must be unique in a given structure or signature.
```

**Comment by def-lkb** [comment]
This case is particularly hard to handle with the design of merlin incremental typechecker (it would mean duplicating the corresponding part of ocaml type-checker, has this occurs at the boundaries between "normal" and "incremental" type-checking).

I am considering closing this as WONTFIX, unless @trefis have another opinion?

**Comment by trefis** [comment]
2015-02-11 11:03 GMT+00:00 def-lkb <notifications@github.com>:
> I am considering closing this as WONTFIX, unless @trefis have another opinion?

I agree, it doesn't seem like detecting that error is worth the trouble.

**Comment by def-lkb** [comment]
It could be done in a later pass by running the normal typechecker on the whole file.
It is also possible to check that a .ml satisfy the .cmi interface at this step. 

However, this won't bring any benefit over running the compiler.
