### ISSUE TITLE
Adding support for the bitstring module

### ISSUE THREAD

**Issue by xguerin** [the-lambda-church/merlin#358]
The [bitstring](https://code.google.com/p/bitstring) module is a lifesaver for those working with bit strings. Unfortunately, it introduces a syntax extension `bitmatch` that is not supported by Merlin. How much trouble would it be to support it ?

**Comment by trefis** [comment]
I will have a look during the week, but at this point it's very unlikely that we will implement support for a new camlp4 extension.
People should consider using PPX (if you have time, you could contribute a ppx extension for bitstring, `match%bitstring ... with` sounds fine), which is supported by merlin.

**Comment by gasche** [comment]
I created [an issue](https://code.google.com/p/bitstring/issues/detail?id=27) on bitstring's upstream.

**Comment by xguerin** [comment]
Thanks, although the `bitstring` project does not seem very active. I'll work on it. Side question: how do you specify PPX to merlin ? With EXT ? I am trying with`ppx_metaquot`, but it does not seem to be working.

**Comment by trefis** [comment]
No, just add the package with `PKG`.
`EXT` is to be used only for camlp4 extensions.

I'm closing this issue as `won't fix` btw.
bitstring should switch to using ppx.
