### ISSUE TITLE
Clearing TypeOf Selection

### ISSUE THREAD

**Issue by rizo** [the-lambda-church/merlin#360]
How to clear the highlighting after the invocation of TypeOf on selection?

**Comment by struktured** [comment]
Vim user here also interesting in how to do this.

**Comment by jordwalke** [comment]
Also interested:
I remapped `<Esc>` to `:noh<CR><Esc>` which nicely clears my search highlight, and I would also like it to clear my Merlin highlight.

**Comment by jordwalke** [comment]
BTW: The command is `:MerlinClearEnclosing`.


It took me a long time to figure out a way to make it work both in Macvim and the Terminal Vim, but here's a script you can include that gracefully degrades if Merlin is not installed or not applicable to your filetype.

It unhighlights the search results, *and* the merlin highlights. Quite handy.


    " http://stackoverflow.com/questions/11940801/mapping-esc-in-vimrc-causes-bizzare-arrow-behaviour
    function! UnhighlightMerlinIfDefined()
      if exists(":MerlinClearEnclosing")
        execute "MerlinClearEnclosing"
      endif
    endfunction


    command -nargs=* DoUnhighlightEverything :call UnhighlightMerlinIfDefined(<f-args>)
    if has('gui_running')
      nnoremap <silent> <esc>  :nohlsearch<return>:DoUnhighlightEverything<return><esc>
    else
      " code from above
      augroup no_highlight
        autocmd TermResponse * nnoremap <silent> <esc> :nohlsearch<return>:DoUnhighlightEverything<return><esc>
      augroup END
    end

**Comment by trefis** [comment]
Sorry for the non response.
`MerlinClearEnclosing` is indeed the right answer.
