### ISSUE TITLE
Error on GADT

### ISSUE THREAD

**Issue by Aaylor** [the-lambda-church/merlin#361]
Hi,

I've an issue using Merlin for Vim, installed by opam.
In fact, when using GADT, Merlin makes two weird thing : 
  *  a warning on a function, which tell that the pattern isn't exhaustive
  *  an error at the top of the file

I've made my test with this simple file:

```ocaml
type _ t =
  | Int   : int   -> int t
  | Float : float -> float t

let get_int : int t -> int = function
  | Int i -> i
```

And there is _:MerlinErrorCheck_ output
```
gadt.ml|1 col 1 error| Error: This pattern matches values of type float t        but a pattern was expected which matches values of type int t        Type float is not compatible with type int
gadt.ml|5 col 30 warning   1| : Warning 8: this pattern-matching is not exhaustive. Here is an example of a value that is not matched: _
```

My merlin version:
```
➜  ocamlmerlin -version
The Merlin toolkit version 2.1.1, for Ocaml 4.02.0
```

I've also made a test with Merlin 2.1.0, and there is the same issue...

Thanks a lot,
Aaylor

**Comment by gasche** [comment]
That is unrelated to the bug but I'm curious: are you really using OCaml 4.02.0? If so, do you have any reason for using 4.02.1 instead?

**Comment by hcarty** [comment]
I have the same error and warning on OCaml 4.02.1.

**Comment by Aaylor** [comment]
There is no real reason, but i've the same errors using OCaml 4.02.1 too.
