### ISSUE TITLE
Special handling for myocamlbuild.ml

### ISSUE THREAD

**Issue by whitequark** [the-lambda-church/merlin#363]
Can you make it so that Merlin acts as if `PKG ocamlbuild` was passed if the file is called myocamlbuild.ml?

**Comment by trefis** [comment]
(Just so history remembers it: https://github.com/the-lambda-church/merlin/commit/27599ad8769d9bc183da0a86bc839cd8d0305582 )

**Comment by whitequark** [comment]
The vim bindings seem like an inappropriate place to do this...

**Comment by trefis** [comment]
It does :)
It's a quick and dirty hack of 2 years ago your issue reminded me about, I just wanted to share it with the world.
