### ISSUE TITLE
Question: How to handle nested, packed module file hierarchies

### ISSUE THREAD

**Issue by tel** [the-lambda-church/merlin#368]
Often when working with deeply nested modules I reflect the nesting structure in my file hierarchy using `.mlpack` files

```
- lib.mlpack = "A\nB\nL"
- src/
    - l.ml/i
    - a.mlpack = "X\nY"
    - b.mlpack = "Z\nQ"
    - a/
      - x.ml/i
      - y.ml/i
    - b/
      - z.ml/i
      - q.ml/i
```

Now, when using Merlin in such a structure it's often the case that it cannot find modules. Typically I structure things a bit like

```
src/a/.merlin = "REC"
src/b/.merlin = "REC"
src/.merlin = "REC"
```

with `.merlin` in the main directory as

```
S src
S src/a
S src/b
B _build/src
B _build/src/a
B _build/src/b
```

Is there a more proper design for helping Merlin to find the right modules in a situation such as this? Thanks!

**Comment by trefis** [comment]
> it's often the case that it cannot find modules

What do you mean?

Also, if the `.merlin` files in the subdirectories only contain `REC` you don't have to have them, merlin will look in the parent directories to find a `.merlin`.

**Comment by tel** [comment]
I mean that if I try to, say,

    open A.X

in `b/z.ml` then merlin will report that `A.X` is unknown but the compile will work cleanly.

**Comment by trefis** [comment]
1. Does it tell you that `A.X` is unbound, or that `A` is unbound?
2. I can't reproduce with just this information, I don't know how to compile that. How do you invoke ocamlbuild?

**Comment by tel** [comment]
I do invoke ocamlbuild. If you add a file `./lib.mllib = "Lib"` and invoke `ocamlbuild lib.cma` it should build. If you do `ocamlbuild lib.cmxa` you'll need a few more files.

A live, related example exists [here](https://github.com/tel/ocaml-cats/blob/master/src/s2/applicative.ml).

When I open this file in emacs and C-c C-x to check for errors Merlin reports that [this line](https://github.com/tel/ocaml-cats/blob/master/src/s2/applicative.ml#L33) has the following error

```
Error: The type constructor t expects 1 argument(s),
but is here applied to 2 argument(s)
```

This occurs because it interprets `Covariant.S` as being defined in [`src/s1/covariant.ml`](https://github.com/tel/ocaml-cats/blob/master/src/s1/covariant.ml) despite there being a "closer" [`Covariant.S`](https://github.com/tel/ocaml-cats/blob/master/src/s2/covariant.ml).

I think that solving either problem ought to solve the other.

**Comment by trefis** [comment]
Alright, in that particular case you then need something like 
```
$ cat src/s1/.merlin
B ./../../_build/src
B ./../../_build/src/s1
$ cat src/s2/.merlin
B ./../../_build/src
B ./../../_build/src/s2
$ [...]
```

I think that corresponds to what ocamlbuild has in its path when compiling each of the .mlpack ( @gasche will confirm?).

**Comment by tel** [comment]
Ah, interesting. I suppose I misunderstood the merlin REC model.

**Comment by tel** [comment]
This is sort of tragic too, of course. Ultimately I have to replicate the entire tree in each leaf...
