### ISSUE TITLE
Feature Request: Support for `-pp` or equivalent (custom frontend parser/reader)

### ISSUE THREAD

**Issue by jordwalke** [the-lambda-church/merlin#370]
I understand all the problems that merlin solves and the *reason* why it is so impressive and important is that it works like a professional grade IDE, telling you a ton of information about your code while it is in an invalid state. However, I was wondering if you could add very *minimal* support for `-pp` extensions. Here is a list of things that would be better than nothing in increasing order of difficulty.

- Ability to pass 100% valid files to `merlin`, with `-pp` flag. Once you make the parse invalid (if your `-pp` program cannot parse it), then you cannot sync the buffers.
- Highlighting type errors on valid parses (with `-pp`), but only highlighting the parse (with `-pp`) errors when the syntax is invalid.
- Ability to do `:Locate` on files that are invalid OCaml parses but valid once ran through the `-pp` processor.
- Ability to do `:Locate` on files that are invalid parses even with `-pp`, but whos buffers were synced when they were recently last valid. It is acceptable if the information is somewhat stale.
- Ability to have very rudimentary autocomplete on files that are not valid OCaml parses, not valid even with `-pp`, but were recently synced when they were last valid. (In this case, the autocomplete would be more like common `ctags` solutions). (The same would apply to `TypeOf` I imagine).

With even just a couple of these, it would then at least be pleasant to navigate/Locate code that depends on `-pp`.

**Comment by trefis** [comment]
I don't understand.

**Comment by jordwalke** [comment]
I created this issue to request minimal support for running ocaml `-pp` preprocessors. The bullet points just enumerate a couple of ideas - some of which seem very easy to implement but at least provide some basic support for viewing errors/`TypeOf`/`Locate` etc.

For example, suppose you were using whitequark's `m17n` preprocessor with the `-pp` flag (or any other basic preprocessor). If some of the bullet points were implemented, you'd at least be able to view the code in Vim and perform some basic `merlin` features on it.

**Comment by trefis** [comment]
My bad, I read `-ppx` instead of `-pp`.

**Comment by jordwalke** [comment]
Do you have any suggestions about how this could be done entirely at the Vim/Emacd plugin level before ever getting proper support from the merlin service?

**Comment by jordwalke** [comment]
Would the easiest way to add a tiny amount of support be to allow the merlin process to optionally accept a binary serialized AST (which I'm sure you're well aware happens here in `driver.ml` of the standard OCaml compiler: https://github.com/ocaml/ocaml/blob/trunk/driver/pparse.ml#L143).

**Comment by def-lkb** [comment]
I am considering adding a better support for non-ocaml lexers, mainly cppo-like, mly or mll (those would also come with specific parsing rules). What are the use cases you are thinking of with your pp ?

One problem with the interface you suggest is that merlin never has complete knowledge of a file: the editor just sends the bit that are relevant for the query, nothing if the file is in sync.

If you want to pp the file, I guess merlin would be responsible for caching the whole file, and calling the pp.
The binary serialized AST is indeed an option, but then it gets messy at a different level, since the editor is now responsible for the pipeline.

**Comment by jordwalke** [comment]
I'm have a mode of syntax that allows two people to collaborate on the same file, each viewing the file in their own customized syntax, without the other party being aware that the other has a different syntax than they do. A third person, who prefers the stock OCaml syntax will simply see stock OCaml syntax, without being aware of the fact that the other two are writing in a wildly different syntax.

This entire toolchain builds on the idea of "AST deterministic formatters", meaning that for any (syntax definition, AST parse) there is exactly one valid pretty printing. AST deterministic formatters essentially become lossy (but not too lossy) AST serializers - which unlocks the power for two people to be collaborating on a single file, with their own "view" of it existing solely in their editor.

To integrate with `merlin`, this means that whenever their custom parser can validly parse their file into a stock OCaml AST, that AST can then be sent to merlin.

Given that, what's the easiest way to integrate with merlin? Should merlin (the Vim/Sublime plugin) allow a custom defined preprocessing hook that first tries to parse into a standard OCaml binary AST format? That would work for me.
