### ISSUE TITLE
merlin-locate-expr

### ISSUE THREAD

**Issue by UnixJunkie** [the-lambda-church/merlin#371]
Hello,

Is there a merlin command to locate an expression the user would enter
interactively (instead of using the one under the cursor like with merlin-locate)?

If not, then that's a feature request for the excellent and amazing merlin.
Thanks for this incredible tool.

**Comment by trefis** [comment]
There is... in vim.
I'll update the emacs mode so it is supported as well.

**Comment by UnixJunkie** [comment]
Thanks a lot ! :+1:
