### ISSUE TITLE
feature request: code folding in vim

### ISSUE THREAD

**Issue by nilsbecker** [the-lambda-church/merlin#373]
ideally, when setting `set foldmethod=syntax` merlin should allow code folding based on semantics. modules, let bindings etc... sorry if this is already implemented but i did not work for me.

**Comment by nilsbecker** [comment]
right now, folding based on indentation is possible but that's really not as good

**Comment by rgrinberg** [comment]
This is not really merlin's job. If you have a recent version of the vim ocaml plugin e.g. my own fork example [1] you should be able to enable it with

``` VimL
let g:ocaml_folding=1
```

[1] https://github.com/rgrinberg/vim-ocaml

**Comment by nilsbecker** [comment]
even better! i was not aware that there were more vim plugins besides merlin and ocp-indent. i looked in the help for the ocaml mode bundled with vim but that does not seem to offer that. is vim-ocaml  intended as a replacement for the built-in ocaml support in the future, or will it remain an addon?

**Comment by nilsbecker** [comment]
actually, it looks like vim-ocaml does indentation, so it is incompatible with ocp-indent, yes?

**Comment by rgrinberg** [comment]
vim-ocaml is basically a more up to date version of the builtin OCaml mode that comes with Vim. It's not incompatible with ocp-indent but you do have to choose who you'd like to do the indentation - vim or ocp.

**Comment by nilsbecker** [comment]
ah, i think i misunderstood. the `indent()` calls in vim-ocaml read the indent level. i thought they set it, which is why i thought it competes with ocp-indent. so basically, i can just install both plugins together iiuc.
