### ISSUE TITLE
ILocate errors when CtrlP is missing

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#378]
Should be more like `:Outline` which is more graceful.

**Comment by trefis** [comment]
That is easy enough to do.
However, I still haven't managed to get ILocate to work, does it work for you? If not, I'll probably just remove the thing and be done with it (I should never have pushed it anyway).

**Comment by rgrinberg** [comment]
I don't really use CtrlP I just wanted to see what it was about and it did seem to work.
