### ISSUE TITLE
Prefix Merlin Vim commands with Merlin

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#379]
Many Merlin commands are using rather common names which sometimes cause annoying conflicts. For example `Locate` in vim-eunuch. I propose to rename the following list by prefixing Merlin.

* Destruct
* ILocate
* Outline
* Locate
* Reload
* Rename
* Occurences
* Use
* AddFlags
* SetFlags
* ClearFlags

This is not exhaustive and some of these already have proper Merlin aliases, so the old forms have to be removed.

**Comment by jordwalke** [comment]
:+1:

**Comment by trefis** [comment]
Fixed by 1094f99b .
