### ISSUE TITLE
Conflicting key mappings.

### ISSUE THREAD

**Issue by jordwalke** [the-lambda-church/merlin#381]
It seems some of the `merlin` key mappings conflict with other plugins. For example, `<tab>` in visual mode conflicts with the popular `Ultisnips` plugin. Can `merlin` have these disabled by default and provide an example keybindings file that people can opt into via some global flag, or copy/paste into their own keybindings config?

**Comment by rgrinberg** [comment]
+1 Please no default mappings.

**Comment by def-lkb** [comment]
Addressed by @hcwndbyw 's pull request! Thanks.
