### ISSUE TITLE
How to jump back from merlin-locate in emacs?

### ISSUE THREAD

**Issue by UnixJunkie** [the-lambda-church/merlin#382]

**Comment by UnixJunkie** [comment]
merlin-locate jumps to the definition.
It would be useful to be able to jump back to the original position.
Or, to have a merlin-locate variant that opens a new buffer before jumping.

**Comment by trefis** [comment]
> merlin-locate jumps to the definition.
It would be useful to be able to jump back to the original position.

`merlin-pop-stack` is the function to call.
It is by default bound to `C-c &`.
When you locate something, a message should be printed in the minibuffer saying "Use C-c & to go back".

> Or, to have a merlin-locate variant that opens a new buffer before jumping.

There is already a bunch of settings to specify whether locate should open a new window, whether it should focus that window.
`M-x customize-group merlin` and then look for locate.

You can easily define your own variants of locate which just locally overwrite these settings before calling locate.

**Comment by UnixJunkie** [comment]
thanks a lot
