### ISSUE TITLE
locate using cmt to a packed library

### ISSUE THREAD

**Issue by ivg** [the-lambda-church/merlin#385]
First of all I'm not sure that it is true for all packed libraries, this is just my guess. So, when I'm trying to locate symbol from `Core_kernel` library it fails with the following output (obtained with `FLG -debug locate:debug,locate.log`):

```log
{"time":166,"level":"info","section":"locate","title":null,"content":"looking for the source of 'uw' (prioritizing .ml files)"}
{"time":166,"level":"info","section":"locate","title":null,"content":"lookup in value namespace"}
{"time":166,"level":"debug","section":"locate","title":null,"content":"present in the environment, but ghost lock. walking up the typedtree."}
{"time":166,"level":"info","section":"locate","title":null,"content":"Core_kernel.Std.uw not in current file..."}
{"time":166,"level":"debug","section":"locate","title":null,"content":"from_path 'Core_kernel'"}
{"time":193,"level":"info","section":"locate","title":null,"content":"inspecting /Users/ivg/.opam/bap.0.9.5-release/lib/core_kernel/core_kernel.cmt"}
{"time":193,"level":"debug","section":"locate","title":null,"content":"File_switching.move_to /Users/ivg/.opam/bap.0.9.5-release/lib/core_kernel/core_kernel.cmt"}
{"time":193,"level":"debug","section":"locate","title":null,"content":"File_switching.allow_movement"}
{"time":193,"level":"debug","section":"locate","title":"loadpath","content":"Saw packed module => erasing loadpath"}
{"time":193,"level":"debug","section":"locate","title":"loadpath","content":"/Users/ivg/.opam/bap.0.9.5-release/lib/core_kernel"}
{"time":193,"level":"debug","section":"locate","title":"loadpath","content":"lib"}
{"time":193,"level":"debug","section":"locate","title":"loadpath","content":"/Users/ivg/.opam/bap.0.9.5-release/lib/ocaml"}
{"time":193,"level":"debug","section":"locate","title":"loadpath","content":"Restored load path"}
{"time":193,"level":"info","section":"locate","title":null,"content":"failed to locate the cmt[i] of 'lib/std.cmx'"}
```

All `cmt` files are available in the system, e.g., 
```
$ ls {core_kernel,std}.cmt
core_kernel.cmt	std.cmt
```

The project seems configured correctly, as I can jump to other libraries, like bap and normal ocaml libraries, that's what make me to think that the problem is with packing.

Just in case,  the system is Mac OS X, and my `.merlin` is:
```
PKG core_kernel
PKG bap
FLG -debug locate:debug,locate.log
```

**Comment by trefis** [comment]
Could you pin merlin to the ocamldoc branch of this repository and try
again?
(I'm not promising this is fixed... But it might be)

Otherwise I'll try to fix that on Monday.

**Comment by ivg** [comment]
With this branch it looks better (at least it jumps from `open Core_kernel.Std` to the `Std` module), but, most of the other stuff still doesn't work, for example, trying to locate `uw` gives the following:
```log
{"time":183,"level":"debug","section":"locate","title":null,"content":"Fallback.set: File \"lib/std_kernel.ml\", line 3, characters 0-20"}
{"time":183,"level":"debug","section":"locate","title":null,"content":"from_path 'Std_internal.uw[val]'"}
{"time":195,"level":"info","section":"locate","title":null,"content":"inspecting /Users/ivg/.opam/bap.0.9.5-release/lib/core_kernel/std_internal.cmt"}
{"time":195,"level":"debug","section":"locate","title":null,"content":"File_switching.move_to /Users/ivg/.opam/bap.0.9.5-release/lib/core_kernel/std_internal.cmt"}
{"time":196,"level":"debug","section":"locate","title":null,"content":"resolves to Common.uw[val]"}
{"time":196,"level":"debug","section":"locate","title":null,"content":"Fallback.set: File \"lib/std_internal.ml\", line 60, characters 0-14"}
{"time":196,"level":"debug","section":"locate","title":null,"content":"from_path 'Common.uw[val]'"}
{"time":196,"level":"info","section":"locate","title":null,"content":"inspecting /Users/ivg/.opam/bap.0.9.5-release/lib/core_kernel/common.cmt"}
{"time":196,"level":"debug","section":"locate","title":null,"content":"File_switching.move_to /Users/ivg/.opam/bap.0.9.5-release/lib/core_kernel/common.cmt"}
{"time":196,"level":"debug","section":"locate","title":null,"content":"failed to find \"Common\" in source path (fallback = false)"}
{"time":196,"level":"debug","section":"locate","title":null,"content":"looking in '/Users/ivg/.opam/bap.0.9.5-release/lib/core_kernel'"}
```
and 
```sh
$ ls common.*
common.annot	common.cmt	common.cmti	common.mli
```

**Comment by trefis** [comment]
Ok I think I know what's going on there.

Merlin found a `.cmt`, so it's expecting to find a `.ml` as well. However there is only a `.mli`. I don't think that .cmt files can be generated without .ml files, so I'm guessing that only mli files were installed by opam, and the ml files are not.
Can you confirm?

Could you also tell locate that you want it to look in `.cmti` and `.mli` in priority and try again?
This can be done with:
- `let g:merlin_locate_preference = 'mli'` in vim
- `(setq merlin-locate-preference 'mli)` in emacs (this might not be the "recommended" way, but I am not an emacs user).

**Comment by ivg** [comment]
Setting `merlin-locate-preference` to `'mli` fixes locate issue on `ocamldoc` branch, but on master it still doesn't work. 

FYI, on ocamldoc branch completion doesn't work for me, says `cond: Wrong type argument: arrayp, nil`. Maybe this is because `merlin-mode` should be also updated...

**Comment by ivg** [comment]
>  I don't think that .cmt files can be generated without .ml files, so I'm guessing that only mli files were installed by opam, and the ml files were not.
Can you confirm?

Yes, this is default behavior of the latest oasis. Install all `cmt*` files, and install `.ml` file iff there is no `mli` file. Since, most packages use oasis this should be very common.

**Comment by trefis** [comment]
> Setting merlin-locate-preference to 'mli fixes locate issue on ocamldoc branch, but on master it still doesn't work.

As expected then. The master branch is broken but the ocamldoc branch will be released soon.

> FYI, on ocamldoc branch completion doesn't work for me, says cond: Wrong type argument: arrayp, nil. Maybe this is because merlin-mode should be also updated...

Yes it should :)
It should be kept in sync with the binary at all time.

> Yes, this is default behavior of the latest oasis. Install all cmt* files, and install .ml file iff there is no mli file. Since, most packages use oasis this should be very common.

Ok, I didn't know that, thank you!
It's probably worth an issue on oasis' bugtracker then.
