### ISSUE TITLE
typed holes

### ISSUE THREAD

**Issue by c-cube** [the-lambda-church/merlin#386]
Merlin is already pretty awesome, and I don't know whether it's been asked already, but here I go:

I would *love* merlin to propose a _typed hole_ mechanism. Basically, it would support a new kind of identifiers (e.g.,  `$foo` since it's currently not valid) that are equivalence to `assert false`: they can have any type. So, an expression with a typed hole somewhere would typecheck if the hole's type is inhabited.

The point is that `:Destruct` becomes much more useful this way, as it could add typed holes in pattern matching branches.

Example:

```ocaml
type foo =
    | A of int
    | B of string

  let f (x:foo) = match x with
    | _
```

and say I call `:Destruct` with my cursor on `_`, it could expand into:

```ocaml
let f (x:foo) = match x with
  | A _ -> $foo1
  | B _ -> $foo2
```

and let me complete the holes `$foo1` and `$foo2`. This should be especially useful with GADTs as each typed hole might have a distinct type. A command `:Refine`, dual to `:Destruct`, could also refine a typed hole depending on its type:

- a typed hole with type `(a * b * c)` would be replaced with `($foo_a, $foo_b, $foo_c)`
- a typed hole with type `a -> b -> c` would be replaced with `fun a b -> $foo_c`
- same for record types, objects, etc.

**Comment by gasche** [comment]
`:Refine` seems similar to the `:Construct` of #366

**Comment by c-cube** [comment]
Wow, thanks @gasche, this PR looks very close to what I had in mind. In particular, having holes for functor arguments seems like a very good idea.

**Comment by def-lkb** [comment]
```ocaml
let f (x:foo) = match x with
  | A _ -> $foo1
  | B _ -> $foo2
```

How is this any better than, say:
```ocaml
let f (x:foo) = match x with
  | A _ -> __
  | B _ -> __
```
?

Is it useful just because of the generated identifiers?

**Comment by c-cube** [comment]
It's not better than `_` or `_1`, `_2` as in #366, indeed. What really matters is that Destruct adds right-hand sides in pattern matching, and that a command Construct/Refine makes it possible to work with `_` in value position.

In fact, I didn't really realize that `_` as a value was allowed by merlin, it's indeed already a kind of typed hole. What is missing is a way of building such holes gradually from their types (introducing arguments, records, functor arguments, tuples...).

**Comment by def-lkb** [comment]
`_` is not a valid expression. That's why @art-w and I used identifiers of the form `__`. 
I get that #366 provides what you are missing? If that's the case, maybe we can close this issue.

That being said, afaic remember, #366 is not really reliable (I might be wrong).

**Comment by trefis** [comment]
> I get that #366 provides what you are missing? If that's the case, maybe we can close this issue.

I don't think we can close the issue, #366 is far from being merged (or mergeable).
