### ISSUE TITLE
Unbound module 'Module'

### ISSUE THREAD

**Issue by dannywillems** [the-lambda-church/merlin#388]
Hi.
I've got an issue with merlin and the module detection (all my projects). It doesn't detect the other files, and I get the "Unbound module 'foo'". Here's an example.
I create a *test* project, and a *.merlin* file in. I wrote "S src" in the *.merlin* files after creating a src directory.
After that, I create a foo.ml file with a foo_f function, and a bar.ml file calling Foo.foo_f (of course, in src dir). I get in vim "Unbound module foo", and so I can't get the autocompletion.

However, when I type ":SourcePath", the src directory is in the path.

Thank you for your help.

EDIT: I install merlin with opam. The others command such as Rename, TypeOf work. Module such as Array of List work perfectly and are detected. The autocompletion works also.

**Comment by dsheets** [comment]
How about `B _build` (or wherever you build your source)?

**Comment by trefis** [comment]
David's solution is the right one, [this page](https://github.com/the-lambda-church/merlin/wiki/emacs-from-scratch#configuring-your-project) might give a little more explaination regarding why this is needed (but only a little :) ).

**Comment by dannywillems** [comment]
Thanks. It's working ! I need to add the complete path. So for my example it's
*B _build/src*.
