### ISSUE TITLE
Unable to get merlin-mode to work

### ISSUE THREAD

**Issue by yxchng** [the-lambda-church/merlin#391]
(load "/Users/yxchng/.opam/system/share/emacs/site-lisp/tuareg-site-file")

(add-to-list 'load-path
   "/Users/yxchng/.opam/system/share/emacs/site-lisp")
(require 'ocp-indent)

 ;; Add opam emacs directory to the load-path
        (setq opam-share (substring (shell-command-to-string "opam config var
   share 2> /dev/null") 0 -1))
        (add-to-list 'load-path (concat opam-share "/emacs/site-lisp"))
        ;; Load merlin-mode
        (require 'merlin)
        ;; Start merlin on ocaml files
        (add-hook 'tuareg-mode-hook 'merlin-mode t)
        (add-hook 'caml-mode-hook 'merlin-mode t)
        ;; Enable auto-complete
        (setq merlin-use-auto-complete-mode 'easy)
        ;; Use opam switch to lookup ocamlmerlin binary
        (setq merlin-command 'opam)

I added this code to .emacs but it doesn't seem to work

it gives me *spurious* error and says 
/usr/local/Cellar/emacs/24.5/Emacs.app/Contents/MacOS/Emacs: /bin/bash: opam: command not found/ocamlmerlin: No such file or directory

How should I solve this problem?

**Comment by def-lkb** [comment]
It seems that `opam` binary is just not reachable from your emacs process.
You should adjust the `PATH` environment variable, or maybe make a symbolic link to `opam` which is reachable system-wide `PATH`.
