### ISSUE TITLE
Help with memory usage in merlin/Emacs

### ISSUE THREAD

**Issue by thranur** [the-lambda-church/merlin#392]
Lately, my Emacs with merlin has been using more memory than usual, because after 1-2h of use, its memory usage is about 1.5 GB, mostly when editing a file of about 7 kLOC.

I had never seen this happen before and I tried updating my merlin to trunk, but it didn't help much.

Restarting merlin via the menu is sufficient to free the memory, but after about one hour of usage, memory usage is once again very high. I'd like to understand why this is happening in the first place. I don't know if it is related to a new file I'm working on, or something else. I do not recall having changed my configuration recently, other than adding a "FLG" line to my .merlin, but I did start working on a different set of files.

I don't know many techniques to try and debug Emacs' memory usage, to obtain more details about it. In the example below, `top` says that the `/home/merlin/ocamlmerlin -protocol sexp` process is using 1.5 GB of physical memory. `pmap <pid>` gives me this, which does not seem terribly useful (it only says that almost all memory is mapped by an `anon`):

```
4814:   /home/merlin/build/bin/ocamlmerlin -protocol sexp
0000000000400000   2860K r-x-- ocamlmerlin
00000000008cb000      4K r---- ocamlmerlin
00000000008cc000   1832K rw--- ocamlmerlin
0000000000a96000     60K rw---   [ anon ]
0000000000ad2000  14776K rw---   [ anon ]
00007f99f9c24000 1431248K rw---   [ anon ]
00007f9a512d9000  90668K rw---   [ anon ]
00007f9a5762d000  15640K rw---   [ anon ]
00007f9a592bb000   2856K r---- locale-archive
00007f9a59947000   2056K rw---   [ anon ]
00007f9a59b49000   1772K r-x-- libc-2.19.so
00007f9a59d04000   2044K ----- libc-2.19.so
00007f9a59f03000     16K r---- libc-2.19.so
00007f9a59f07000      8K rw--- libc-2.19.so
00007f9a59f09000     20K rw---   [ anon ]
00007f9a59f0e000     12K r-x-- libdl-2.19.so
00007f9a59f11000   2044K ----- libdl-2.19.so
00007f9a5a110000      4K r---- libdl-2.19.so
00007f9a5a111000      4K rw--- libdl-2.19.so
00007f9a5a112000   1044K r-x-- libm-2.19.so
00007f9a5a217000   2044K ----- libm-2.19.so
00007f9a5a416000      4K r---- libm-2.19.so
00007f9a5a417000      4K rw--- libm-2.19.so
00007f9a5a418000    140K r-x-- ld-2.19.so
00007f9a5a44b000    516K rw---   [ anon ]
00007f9a5a50d000   1048K rw---   [ anon ]
00007f9a5a638000      8K rw---   [ anon ]
00007f9a5a63a000      4K r---- ld-2.19.so
00007f9a5a63b000      4K rw--- ld-2.19.so
00007f9a5a63c000      4K rw---   [ anon ]
00007fff2cd56000    132K rw---   [ stack ]
00007fff2cdd8000      8K r-x--   [ anon ]
ffffffffff600000      4K r-x--   [ anon ]
 total          1572888K`
```

If you have any tips about what could cause it or how I could try to debug it (e.g. by adding emacs-lisp calls in merlin.el, or modifying the OCaml code), I'd like to investigate it further.

**Comment by def-lkb** [comment]
Are you using libraries such as core?

**Comment by def-lkb** [comment]
More detailed response: I propose to first investigate whether this really is a memory leak.
Your heap is 1.5GB big, let's consider that's the live set is half that, say 700MB (50% unused memory is a reasonable approximation, given the GC is not tuned and that a lot of memory might be allocated during intermediate processing).

What can fill those 700MB? Merlin is caching a lot of things.
All the cmi and cmt that have been used are kept in memory. The size of your file alone is almost completely irrelevant − with 7000 LOC, maybe 50MB are allocated for your specific buffer (tha.
If you worked on different buffers, the few last 10 ones are kept around, to make access quicker.
If you recompile often (that is a lot cmi files change), they will be reloaded from disk when needed, but this memory won't be immediately recycled, it will just be garbage waiting around, and that might be reused much later.

**Comment by thranur** [comment]
Thank you for the information, it is indeed likely that I am compiling many more files now and that could be the reason I am noticing such a difference in memory usage. I was used to letting the Emacs buffer open for days without ever having any memory issues, so I thought that it could be something related to my Emacs usage.

I will update the title to reflect "usage" instead of "leak", and will try to more closely monitor its behavior. I will still leave it open for a few days, just in case I have some relevant data later, and will close it if I have nothing more to add.

**Comment by def-lkb** [comment]
If you think that can help you, I can instrument code a bit, manually calling Gc and dumping memory statistics. However, this will have to wait for a week.

**Comment by thranur** [comment]
After two weeks of work on more "standard" files, it seems indeed the cause was the size of the files I was editing. It could also eventually be due to other emacs-lisp code (sometimes tuareg behaves strangely, especially after leaving 30 buffers open for a few months...), but in any way I did not see any actual memory leak, and I am using "restart merlin" more liberally now, just in case. Thanks for the tips, and sorry about the false alarm!
