### ISSUE TITLE
In the vim plugin the function FindFile doesnt handle filenames with spaces in the path

### ISSUE THREAD

**Issue by nilehmann** [the-lambda-church/merlin#393]
In the vim script the function merlin#FindFile doesnt handle filenames that has spaces in the path. The problem is in file autoload/merlin.vim line 78 
     
    if fname != None: vim.command("e "+ fname)

In linux adding this fix the problem

    if fname != None: vim.command("e "+ fname.replace(' ','\\ ')

I don't know if windows handle this in another way. Also it would be posible to do a more general escape of the characters.

**Comment by def-lkb** [comment]
Fixed, thank you.
