### ISSUE TITLE
Ocamlscript syntax support

### ISSUE THREAD

**Issue by struktured** [the-lambda-church/merlin#394]
Merlin rightly generates syntax errors about the code preceding the ```--`` `for headers of [ocamlscript](https://github.com/mjambon/ocamlscript/) files. The header looks something like this:

```Ocaml
#!/usr/bin/env ocamlscript
Ocaml.packs := ["extlib";"re";"unix";"cmdliner";"fileutils"]
Ocaml.sources := "some_source.ml"

--
let () = "hello world"
```

Some other examples are [here](https://github.com/mjambon/ocamlscript/tree/master/examples). 

If a ```.merlin``` file has ```ocamlscript``` listed as a package definition, it would be nice if it interpreted the header appropriately, including (maybe) adding all the sources referenced by "packs" (I don't need this feature but it would be cool). At the very least if it ignored the header that would be an improvement.

**Comment by rgrinberg** [comment]
Wouldn't it be better to just port ocamlscript to use ppx?

**Comment by struktured** [comment]
Fair enough but the first line still has to be ignored as it's purely for
the shell environment.

**Comment by trefis** [comment]
I already is.

**Comment by struktured** [comment]
Sorry, what already is? The first line is ignored if it's ```#!/some/shell```? I see that it is not for me, it shows an error on that line. Or do you mean that ocamlscript is already using ppx?

**Comment by def-lkb** [comment]
The first line should be ignored yes. Which version of merlin are you using?

**Comment by struktured** [comment]
I am using merlin 2.1.2 for OCaml 4.02.1 on two different kubuntu 14 machines. On one of them it doesn't show a syntax error but on the other it does. I spent a couple hours trying to track the difference in configuration to no avail. 

 I will consider this something wrong with my own setup rather than leaving the issue open.  Thanks.

**Comment by struktured** [comment]
Now I'm getting a bit desperate. Did a clean sweep of my opam repo but still getting the syntax error.
Screen shot, some diagnostic information below:

![merlin-syntax-error](https://cloud.githubusercontent.com/assets/5060002/7685735/4d5b5c7c-fd5e-11e4-80bb-f7c80483481b.png)

```
$ 
$ opam --version
1.2.0                                                                                                                                                                                         
$ ocamlmerlin -version
The Merlin toolkit version 2.1.2, for Ocaml 4.02.1
$ which ocamlmerlin
/home/cpiccion/.opam/4.02.1/bin/ocamlmerlin
$ opam switch
4.02.1  C 4.02.1  Official 4.02.1 release
--     -- 3.11.2  Official 3.11.2 release
--     -- 3.12.1  Official 3.12.1 release
--     -- 4.00.0  Official 4.00.0 release
--     -- 4.00.1  Official 4.00.1 release
--     -- 4.01.0  Official 4.01.0 release
--     -- 4.02.0  Official 4.02.0 release
# 96 more patched or experimental compilers, use '--all' to show
$ 
$ ocamlscript -version
2.0.4
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  7 2015 22:27:08)
Included patches: 1-560
Compiled by cpiccion@pp-wk-cpic-02
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   -perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            -ruby            +writebackup
+digraphs        +mksession       +scrollbind      +X11
-dnd             +modify_fname    +signs           +xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        -mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl    -ldl
$
$ uname -a
Linux pp-wk-cpic-02 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by struktured** [comment]
The .merlin file (scripts in a subfolder as suggested by the config):

```
PKG csv oml csv extlib re cmdliner fileutils ocamlscript containers
SRC scripts/**
B scripts/**
````

**Comment by trefis** [comment]
That doesn't look like a message from merlin.
Are you sure your "syntastic checker" is merlin?

Fwiw merlin tells me "Syntax error, expecting `#' or expression" on the --,
which is what I would expect.
The message you get looks like it's generated from camlp4.

2015-05-18 13:10 GMT-04:00 Carmelo Piccione <notifications@github.com>:

**Comment by trefis** [comment]
2015-05-18 13:13 GMT-04:00 Thomas Refis <thomas.refis@gmail.com>:
>
> That doesn't look like a message from merlin.
> Are you sure your "syntastic checker" is merlin?

Note: you can check that with "let g:syntastic_ocaml_checkers<RET>"
and see if it says "['merlin']" or something else.

**Comment by struktured** [comment]
Nice, you found it! I had it defined on this machine as

```let g:syntastic_ocaml_check = ["merlin"]```

instead of

```let g:syntastic_ocaml_checkers = ["merlin"]```

Thanks @trefis for the debugging help!
