### ISSUE TITLE
type error : string/3 vs string/15

### ISSUE THREAD

**Issue by Saroupille** [the-lambda-church/merlin#397]
I had an issue with Ocaml (something related to -fpic). So now I use a new version of Ocaml from the svn repository. Then I reinstalled merlin with opam. And now, I have a lot of theses errors : 
`This expression has type string/3 but and expression was expected of type string/15". 

Of course, if I compile with ocamlc, there is no issue. I have no idea what is the problem. Is this something related to a newest version of Ocaml ?

**Comment by trefis** [comment]
Do you have a reproductible exemple?
Also, which version of merlin are you using?

**Comment by Saroupille** [comment]
On this example :

```ocaml
let string = "hello"
let doubt = "world"

let _ = Printf.printf "%s\n" string^doubt;	      
```

Error give me an error on string saying the error above. 

`ocamlmerlin` give me this 

`The Merlin toolkit version git-c355b2bdd85cf524ef468131500987ff4f780e6a, for Ocaml 4.03.0+dev7-2015-02-08`

**Comment by trefis** [comment]
This is indeed a bug on our side, note that your code doesn't typecheck, but even if you fix it (by adding the missing parentheses) merlin will give you the exact same error message.
This is broken only for the "trunk" (read: "ocaml trunk support") version of merlin, which is a lot less tested and should be considered "experimental".

I don't know yet what the problem is, I'll try to have a look in the next few days.

**Comment by Saroupille** [comment]
Did you find the problem ? 

By the way, I didn't find section ocaml trunk support, where is it ?

**Comment by trefis** [comment]
> Did you find the problem ?

I didn't look at this specifically, but we are trying a new mechanism for type recovery on the `new-typer` branch. You might want to try that (beware: it might work, but it might also be terribly broken).

> By the way, I didn't find section ocaml trunk support, where is it ?

I guess you're referring to my "(read "ocaml trunk support")", where I meant "should be understood as" when I wrote "read".
There is actually nothing to read. Sorry!

**Comment by def-lkb** [comment]
The new-typer branch doesn't support trunk.

**Comment by def-lkb** [comment]
I just pushed support for trunk in [new-typer](https://github.com/the-lambda-church/merlin/tree/new-typer/src).
(This branch supports trunk only, 4.02 support coming soon).
