### ISSUE TITLE
js syntax extension is broken?

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#398]
It seems like the js_of_ocaml syntax extension isn't being interpreted anymore for me.

For example, I have merlin configured to use the extension in cohttp:
https://github.com/mirage/ocaml-cohttp/blob/master/.merlin#L10

Try loading the file in Vim:
https://github.com/mirage/ocaml-cohttp/blob/master/js/cohttp_lwt_xhr.ml#L32

I've recently upgraded to merlin master but I haven't opened that file in a while so perhaps this wasn't broken recently.

**Comment by def-lkb** [comment]
Yep, that's a problem, I will take a look at that.

**Comment by def-lkb** [comment]
Broken by 5f87f58bd82f2660d064cd6c82521b7eeaad9a67.

**Comment by def-lkb** [comment]
Fixed in HEAD (c7c6c581c76477f45dfdfb62f8361d76191baade). This will need more work to have proper support for 4.03, but we can take care of that later.

**Comment by Drup** [comment]
Well, in 4.03, everyone will use the ppx instead and there will be no issue anymore, right ?! :]

**Comment by dbuenzli** [comment]
@Drup Any documented guidance to migrate ?

**Comment by Drup** [comment]
Not yet, I should indeed write one. The documentation is [here](https://github.com/ocsigen/js_of_ocaml/blob/master/lib/ppx/ppx_js.mli).

The biggest change is that `foo##bar(x)` is now `foo##bar x`.

Not this all still in dev version of js_of_ocaml and needs ocaml 4.02+trunk.

**Comment by def-lkb** [comment]
And is precisely the reason why merlin broke, there was a conflict around meaning of '##' token.
The fix is to favor merlin implementation of js syntax over 4.02+trunk (and we will fix the fix later).
