### ISSUE TITLE
Tag generation

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#399]
Would be great if merlin supported tag generation. It might seem redundant because merlin has its own mechanism to go to definition but the point is that editors have very good integration with tag files that would be hard for merlin to replicate. For example, searching for tags, highlighting them in a buffer, navigating back and forth, etc.

[otags](http://askra.de/software/otags/) but it doesn't work with ppx and is annoying to use.

**Comment by trefis** [comment]
I don't feel like this is the job of merlin, plus a program which postprocess cmts to produce tag files seems pretty easy to do.
