### ISSUE TITLE
Problem with js_of_ocaml type checking

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#401]
Not entirely sure if this is a problem but it seems like merlin accepts the following snippet:

``` ocaml
let () =
  (jsnew Js.date_now ())##getTime()
```

But compiling it with js_of_ocaml will reject it with

```
Error: This expression has type float but an expression was expected of type unit
```

**Comment by def-lkb** [comment]
This problem is fixed in master, but you said there was still problems with completion.
Could you be more specific?

**Comment by rgrinberg** [comment]
Hmm it seems to be fixed. Will re-open if I encounter a problem again.
