### ISSUE TITLE
Go to definition failure

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#406]
1) Clone https://github.com/mirage/ocaml-cohttp

2) visit the `Repsonse.write` at https://github.com/mirage/ocaml-cohttp/blob/master/lwt/cohttp_lwt.ml#L407

3) Try going to definition.

4) Observe that merlin is unable to find the definition.

Ideally, merlin would go to the definition the functor that created this function.

**Comment by trefis** [comment]
So, it fixes your use case, but it might break somewhere else (© reliable software).
I haven't really tested for any regression yet, and would appreciate it if you could test this (i.e. before I do another release) and report any problem :)
