### ISSUE TITLE
How can I set so merlin supports MetaOCaml?

### ISSUE THREAD

**Issue by marklrh** [the-lambda-church/merlin#408]
Is it possible to set merlin so it supports [MetaOCaml](http://okmij.org/ftp/ML/MetaOCaml.html) syntax?

**Comment by def-lkb** [comment]
This [metaocaml](https://github.com/the-lambda-church/merlin/tree/metaocaml) branch should provide basic support for MetaOCaml :). Let me know if it works as you expect.

**Comment by marklrh** [comment]
Put a small note here for people reading this issue in the future
One needs to add ``EXT meta`` to tell merlin to enable MetaOCaml supoort
