### ISSUE TITLE
B _build/** does not consider files under _build/ itself

### ISSUE THREAD

**Issue by marklrh** [the-lambda-church/merlin#413]
If there is no subdirectory in _build/ and one still uses ``B _build/**`` in his .merlin file, Merlin will warn.
The solution is to change ``B _build/**`` to ``B _build/``. However, since ``**`` means let merlin consider all files in ``_build`` recursively, the above behavior is actually an issue. 

It's been fixed by @def-lkb . I'll just open an issue for historical purpose

**Comment by def-lkb** [comment]
Thanks, fixed in ac5d7e5817a674c4f155d1cf62dc408849efbefb
