### ISSUE TITLE
Merlin doesn't seem to play well with switches

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#421]
I have an opam switch that is aliased to 4.02.3, created with:

```
opam switch ppp --alias-of 4.02.3
```
I've installed merlin on this switch, etc but it seems like running merlin in this switch confuses the syntax checker:

```
  /Users/rgrinberg/... and /Users/rgrinberg/.opam/4.02.3/lib/cohttp/cohttp_async.cmi make inconsistent assumptions over interface Cohttp_async
```

Where my `ppp` switch has a pinned version of cohttp from github.

Is merlin supposed to handle this situation properly?

**Comment by def-lkb** [comment]
In the general case, no, merlin is not supposed to work: the typechecker is selected at build time, so you will have to build one merlin per switch.

In the special case of an alias, the typechecker version stays the same, only the path to standard library may need update.

This can be worked around, it would be nice to diagnose the exact problem.
I would like to solve both problems in a latter version of merlin: by packing all versions of the typechecker in a single binary, and offering more flexible selection (or even automatic) of standard lib.

Could you print the full paths, as well as output of `ocamlmerlin -version`?

**Comment by def-lkb** [comment]
Ok I misunderstood your initial message, you have merlin installed in that switch…
Still, could you:
- share output of `ocamlfind printfconf` in both switches,
- check the full path of merlin binary (procfs?),
- full error message.

**Comment by rgrinberg** [comment]
`ocamlfind printfconf`:

Aliased switch:
```
Effective configuration:
Configuration file:
    /Users/rgrinberg/.opam/pgd/lib/findlib.conf
Search path:
    /Users/rgrinberg/.opam/pgd/lib
Packages will be installed in/removed from:
    /Users/rgrinberg/.opam/pgd/lib
META files will be installed in/removed from:
    the corresponding package directories
The standard library is assumed to reside in:
    /Users/rgrinberg/.opam/pgd/lib/ocaml
The ld.conf file can be found here:
    /Users/rgrinberg/.opam/pgd/lib/ocaml/ld.conf
```

4.02.3 original switch:
```
Effective configuration:
Configuration file:
    /Users/rgrinberg/.opam/4.02.3/lib/findlib.conf
Search path:
    /Users/rgrinberg/.opam/4.02.3/lib
Packages will be installed in/removed from:
    /Users/rgrinberg/.opam/4.02.3/lib
META files will be installed in/removed from:
    the corresponding package directories
The standard library is assumed to reside in:
    /Users/rgrinberg/.opam/4.02.3/lib/ocaml
The ld.conf file can be found here:
    /Users/rgrinberg/.opam/4.02.3/lib/ocaml/ld.conf
```

Merlin path:

aliased switch: `/Users/rgrinberg/.opam/pgd/bin/ocamlmerlin`
4.02.3: `/Users/rgrinberg/.opam/4.02.3/bin/ocamlmerlin`

Full error:

```
 1 orca/src/orca_client.ml:1 col 1 error: Error: The files /Users/rgrinberg/godzilla/_build/base/src/pgd.cmi and /Users/rgrinberg/.opam/4.02.3/lib/cohttp/cohttp.cmi make inconsistent assumptions over interface Cohttp↲
```

**Comment by Drup** [comment]
I use lots of aliased switches and never had any issue. Are you sure it's not just an issue of remaining build artifact (or hardcoded path to merlin in your config) ?

**Comment by rgrinberg** [comment]
I did a clean build though and I'm not using oasis so I don't have any leftovers like setup.data.

I also don't think I've hard coded the path to merlin b/c `$ which merlin` in the shell and inside vim points to the switch local merlin.

However, the information I posted does make it seem like it's a problem with my setup.

**Comment by rgrinberg** [comment]
This issue was due to my own stupidity. I use merlin's vim files from my own clone and it looks like I also had some build artifacts remaining in that directory. `merlin#selectBinary` was picking up the binary in that directory rather than the one in switch.

Sorry for the noise.
