### ISSUE TITLE
Syntax error: let (+=) = 1

### ISSUE THREAD

**Issue by keleshev** [the-lambda-church/merlin#423]
After I added the line that integrates syntastic and merlin:

```vim
let g:syntastic_ocaml_checkers = ['merlin']
```

I got the following spurious syntax error:

```
Syntax error inside let, expecting `module', <pattern>, `::', `)' or <operator>
```

In this file:

```ocaml
let (+=) = 1
```

If I change the operator to `(+)` or `(=+=)` or `(+-=)` it goes away. I checked and `(+=)` is parsed fine by both caml4p and normal OCaml parser. I'm using OCaml 4.01.0.

**Comment by def-lkb** [comment]
`+=` is reserved in 4.02, and merlin follows the lexical rules of 4.02.
If it is really important for you, I can write a patch, but be aware that support for 4.01 is about to be dropped completely.

**Comment by gasche** [comment]
`( += )` is still a valid infix identifier in 4.02 (I just checked). Similarly, `=` is used in the syntax of type declarations, but still a valid infix identifier.

**Comment by def-lkb** [comment]
Obviously, I updated the lexer and forgot about the grammar. Pffff, and yes, it works with merlin for 4.02.
Sorry about that, fix coming.

**Comment by def-lkb** [comment]
Fixed in git.
