### ISSUE TITLE
Merlin gets messed up occasionally

### ISSUE THREAD

**Issue by bluddy** [the-lambda-church/merlin#428]
I'm on then latest merlin from opam. I've noticed that occasionally, I'll save the file in vim, and merlin will get completely confused. It suddenly won't recognize any identifiers, highlighting source errors everywhere. There used to be a command to reset merlin, but I can't find it any longer.

**Comment by def-lkb** [comment]
Could you get a screenshot if that happens?
Merlin should synchronize automatically. What you describe could happen in the middle of a build, and saving one more time should fix it.

If it can't grab the changes, it get desynchronized with the fs somehow... What is your OS and filesystem?

**Comment by def-lkb** [comment]
Ping.

**Comment by bluddy** [comment]
Haven't been able to observe this for a while. I'll close it, and reopen if it happens again.
