### ISSUE TITLE
`:MerlinToggleTypeHistory` errors out on first run [Vim]

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#432]
Just edit any OCaml file with vim and run `:MerlinToggleTypeHistory`. I get the following:

```
Error detected while processing function merlin_type#ToggleTypeHistory..merlin_type#HideTypeHistory:
line    6:
E16: Invalid range: 2wincmd w
```

Subsequent calls to `:MerlinToggleTypeHistory` seem to work. Why is it even calling `HideTypeHistory`? It should be trying to show it.

**Comment by def-lkb** [comment]
Vim was doing horrible things it seems. I pushed a work around.
