### ISSUE TITLE
Error: Unbound Modules when S contains B

### ISSUE THREAD

**Issue by trevorsummerssmith** [the-lambda-church/merlin#434]
Hi,
First -- thanks for Merlin. It is amazing.

If one creates a .merlin with

    S .
    B _build/**

Merlin will not recognize the modules in the project with  `Error: Unbound module`. This is reproducable with a trivial repo with a foo.ml:

    let f x =
      Bar.good_fun x

and bar.ml

    let good_fun x =
      x + 1

This test case works correctly if given a structure where source does not overlap with build, eg (a more sensible and standard):

    S src
    B _build/**

Perhaps this is related to/the same as #428 @bluddy and #312 @dbuenzli?

Trevor

**Comment by def-lkb** [comment]
I think it is related to https://github.com/the-lambda-church/merlin/issues/413
Just add `B _build` manually or update to a git version.

Sorry for the inconvenience :). Tell me if this fixes your issue.
