### ISSUE TITLE
Relative path issue with ppx_blob

### ISSUE THREAD

**Issue by bbc2** [the-lambda-church/merlin#435]
With a project having the following layout:
```
> tree
.
├── hello.txt
└── src
    └── test.ml
```
With `src/test.ml` being:
```ocaml
print_string [%blob "../hello.txt"]
```

It compiles well with `ocamlbuild -use-ocamlfind -package ppx_blob -I src test.native`, but if I edit the source with Vim: `vim src/test.ml`, Merlin reports the following error:
```
[%blob] could not find or load file ../hello.txt
```
On the other hand, if I open the source from within `src/`, with `vim test.ml`, no errors are reported.

It looks like there is an issue with the path in which the included file is looked for, although I'm not sure whether it's due to ppx_blob or Merlin.

**Comment by def-lkb** [comment]
I confirm, Merlin doesn't set the correct working directory when invoking ppx, this will be fixed (although which one is the correct one is not clear).

**Comment by def-lkb** [comment]
The [ppx-chdir](https://github.com/the-lambda-church/merlin/tree/ppx-chdir) branch attempts to fix that.

**Comment by bbc2** [comment]
Two points:
* Commit 4514e51 causes me troubles with `ppx_blob` (and `ppx_tools`, which is implicitly required):
  * When I open `src/test.ml` with vim: the following message appears and garbles my buffer (C-l cleans it up):

     ```
Sys_error("/t[%/camlppx9e1405: No ]uch file or directory")
```

  * When I run `:MerlinErrorCheck`, I get the following text in my minibuffer:
    ```
Error detected while processing function merlin#Errors..merlin#ErrorLocList:Sys_error("/tmp/camlppxd17e8a: No such file or directory")
                                                                                                                                      
line    9:
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/bertrand/.opam/4.02.3/share/merlin/vim/autoload/merlin.py", line 434, in vim_loclist
    errors = command("errors")
  File "/home/bertrand/.opam/4.02.3/share/merlin/vim/autoload/merlin.py", line 170, in command
    return merlin_process().command(*cmd)
  File "/home/bertrand/.opam/4.02.3/share/merlin/vim/autoload/merlin.py", line 138, in command
    raise Error(content)
merlin.Error: {u'message': u"Error: External preprocessor does not produce a valid file\nCommand line: /home/bertrand/.opam/4.02.3/lib/p
px_blob/./ppx_blob '/tmp/camlppxd17e8a' '/tmp/camlppxe7b08a' &> /dev/null\n", u'valid': True, u'type': u'type'}
Press ENTER or type command to continueSys_error("/tmp/camlppxf1461a: No such file or directory")
```

* If I remove this commit from the ppx-chdir branch, however, I can work as usual with Merlin, but no improvement regarding `ppx_blob`'s path.  I've tried to debug a bit and it seems like `buffer.path` is `None` in my case.

**Comment by def-lkb** [comment]
Ok, I reverted the commit you mentioned in this branch. Let fix things one after the other.
Can you try with the current HEAD of this branch? It works on my local system.

**Comment by bbc2** [comment]
That's great. bed3310 fixes the problem with the path for ppx_blob.

I also tried at home and didn't have any problem with 4514e51.  I don't really understand what was going on.  At work, your new commit b4eed27 seems to work (I haven't tried this last one at home).

**Comment by def-lkb** [comment]
Well, the command is evaluated using `system(3)`, interpretation is up to the system shell.
The error you described is what happens when '&> /dev/null' is interpreted as arguments rather than redirection.
So check what is your system shell on the different machines.

**Comment by bbc2** [comment]
I use fish on all my machines.  However, it seems like OCaml uses `/bin/sh` to execute what is passed to `Sys.command` (`Sys.command "which $0"`).  On my work machine (Debian Jessie), this is a symlink to `/bin/dash`, which doesn't understand `&>` (`echo plop &> /dev/null` prints `plop` and seems to fork).

**Comment by dbuenzli** [comment]
@bbc2 OCaml doesn't use `/bin/sh` OCaml [uses](https://github.com/ocaml/ocaml/blob/b860d631458802c8685aa59c9d7b66a9225fcedb/byterun/sys.c#L318-L335) the POSIX [`system`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/system.html) call which mandates an `sh` shell (or something compatible).

**Comment by def-lkb** [comment]
@dbuenzli which happens to be `/bin/sh` with glibc: http://linux.die.net/man/3/system

**Comment by dbuenzli** [comment]
Oh, but @def-lkb, the syntax you use is not POSIX `sh`. See [here](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_07) for redirections. 

You should rather have something like (with windows compatibility included): 

```ocaml
 let null = match Sys.os_type with "Win32" -> " NUL" | _ -> "/dev/null" in
 Printf.sprintf "cmd arg 2>%s" null
```

**Comment by def-lkb** [comment]
Thanks for windows compat. The equivalent would be '> %s 2> %s' null null.
I wonder if it would not be better to redirect both merlin and ppx processes stderr to a log file however?!

**Comment by dbuenzli** [comment]
> The equivalent would be '> %s 2> %s' null null.

Not sure about the space. Do use `1>%s 2>%s` (and the exact strings I mentioned for `null`) that's what I do in [cmdliner](https://github.com/dbuenzli/cmdliner/blob/1d9fd775b033a709a3436d9ddf57c67d0969921d/src/cmdliner.ml#L383) and it seems to work on a wide range of platforms.

**Comment by def-lkb** [comment]
Included in master.
