### ISSUE TITLE
resolve_path in libfindlib from ubuntu's default repository does not have the right signature

### ISSUE THREAD

**Issue by Michael-A-D** [the-lambda-church/merlin#439]
When compiling the current master (./configure and make), configure did not report any problems, but I have a compilation due to unmatching signatures of resolve_path function from libfindlib.

My version is:
```
val resolve_path : ?base:string -> string -> string
```

While you seem to expect something close to:
```
val resolve_path : ?explicit:bool -> ?base:string -> string -> string
```
I did a local fix by changing src/kernel/dot_merlin.ml to:
```
let resolve_path = Findlib.resolve_path ~base:d in
```

I had to assume the behaviour of resolve_path in my findlib version is equivalent to "resolve_path ?explicit:true" in the expected version (I did *not* check that).

I had this issue with both Ubuntu 14.04 and 15.14 official repositories. 

Closest thing I found to a version number for libfindlib is this comment: 
```
$Id: findlib.mli 189 2013-01-14 17:10:28Z gerd $
```

**Comment by def-lkb** [comment]
This is a problem, we can't easily maintain compatibiliy with different versions of findlib.
I will think of adjusements in the configure script.

Out of curiosity, why are you not using opam?

**Comment by Michael-A-D** [comment]
Simply because I like to maintain as many libs as possible with apt-get, in order to make all updates available in the same place. I did not have any obligations to use opam until now, so I never took time to set it up. 

So it seems that my libs are obsolete and I could have solved this by installing them from opam. If that's the case, I guess you should close this!

Thanks for your time!

**Comment by def-lkb** [comment]
I pushed a simple fix in master.
Btw, which version of OCaml is provided by ubuntu? We will soon drop support for older versions, it's already not that good.

**Comment by Michael-A-D** [comment]
On both 14.04 and 15.04, ocamlc version is 4.01.0.
