### ISSUE TITLE
cannot install merlin new-typer branch

### ISSUE THREAD

**Issue by marklrh** [the-lambda-church/merlin#440]
Hi, def

Recently I've been using Merlin to help me read source of compiler. I wrote this [quick tutorial](https://github.com/ocamllabs/compiler-hacking/wiki/Getting-started#use-merlin-when-hacking-compiler) about how to set up merlin. These steps work pretty well.

Today, I tried again and opam needs to install merlin (the new-typer branch). The following error message shows up. 

````
File "src/config/my_config.ml", line 2, characters 91-104:
Error: This expression has type [> `OCaml_4_00_1 ]
       but an expression was expected of type
         [ `OCaml_4_02_0 | `OCaml_4_02_1 | `OCaml_4_02_2 | `OCaml_4_03_trunk ]
       The second variant type does not allow tag(s) `OCaml_4_00_1
make[2]: *** [src/config/my_config.cmx] Error 2
make[1]: *** [native-code] Error 2
make: *** [ocamlmerlin] Error 2
````

How to restore this error:
1. pull the latest trunk
2. build and install, config env to use this newly-built compiler
3. install merlin (``opam pin add merlin https://github.com/the-lambda-church/merlin.git#new-typer``)

**Comment by def-lkb** [comment]
New-typer branch is no longer maintained, most stuff has been merged in master.
Magic numbers were updated, but not the typechecker, so it will likely not work with current master.

I have to patch merlin typechecker, you'll have to be patient.

**Comment by marklrh** [comment]
thanks. btw, do u personally use Merlin when working on compiler?

**Comment by def-lkb** [comment]
Yes. I work a lot on stable version (4.02.3), and port patches later.
On Merlin side, I port the typechecker for trunk from time to time.

**Comment by def-lkb** [comment]
Updated support for trunk in [browse-node](https://github.com/the-lambda-church/merlin/tree/browse-node).

**Comment by lijunsong** [comment]
Well, it seems browse-node is deleted. @marklrh you might want to update the tutorial.

**Comment by marklrh** [comment]
@lijunsong Thank you. Updated. Make sure you use Merlin 2.3.

**Comment by lijunsong** [comment]
Thanks. I got compilation error in Merlin master. I've switched to Merlin 2.3.
