### ISSUE TITLE
Emacs menu - Add a flag

### ISSUE THREAD

**Issue by Fourchaux** [the-lambda-church/merlin#443]
Merlin_master, Emacs mode

With the Emacs Merlin menu / Add a flag :

Giving an incorrect flag (e.g.: -w-3) followed by a correct one (e.g.: -w -3) display the 'old'
error message ( Unknown flags "-w-3").

Would be nice to have an automatic clearing after an incorrect flag (instead of a manual 'Clear flags')

**Comment by def-lkb** [comment]
I think this clear / add flag interface is wrong.

We should only have set flag, prefilled with the actual flags.
What would you think of that?

**Comment by Fourchaux** [comment]
Displaying somewhere the actual flags setting would be great. Please do it. (and also the meaning of the flags, but well... RTFM...)

You want to suppress Add/Clear flags in the Merlin menu.
So, the only way to change the flags will be the current modification of the FLG line in the .merlin file. 
OK why not ?

**Comment by def-lkb** [comment]
Implemented, there is now a "Set flags" in merlin menu.
Feel free to reopen if the behavior to further discuss the behavior.
