### ISSUE TITLE
MerlinLocate broken by --keep-locs

### ISSUE THREAD

**Issue by bbc2** [the-lambda-church/merlin#446]
If I run `:MerlinLocate` in Vim on a symbol declared in another file, it should switch buffers and put the cursor on that declaration.  Unfortunately, if I compile my project with `true: keep_locs` in `_tags` (there's also `bin_annot`, which is necessary of course), the cursor still moves to the correct coordinates but stays in the same buffer.  Therefore, it does not end up on the expected declaration at all. I get this behavior on 2.2 and master.

**Comment by trefis** [comment]
https://github.com/the-lambda-church/merlin/commit/4b8d994f8547023850d335f7afe05cdc398d088a fix this problem (it's on the branch `locate-keep-locs` if you want to try it).

I didn't push it on master because I'm afraid it might break something else, somewhere... Please try it, let me how it goes for you.

**Comment by bbc2** [comment]
Thanks for the fix.  It seems to work for me too.

**Comment by Khady** [comment]
In emacs:

- When I try to locate a value that is defined previously in the same file, it opens a second buffer and moves the cursor to it
- If I try to locate a value from another file, It has troubles with the path. It opens an empty file in new directory.

**Comment by trefis** [comment]
> When I try to locate a value that is defined previously in the same file, it opens a second buffer and moves the cursor to it

Yep, I expected that one.

> If I try to locate a value from another file, It has troubles with the path. It opens an empty file in a new directory.

I shouldn't be surprised by that one.
It is fixable though, patch coming soon (i.e. in the next few hours)

**Comment by trefis** [comment]
Note: if you mix the two problems you mentioned, your editor will open a new buffer on an empty file named like the one you located from.
Hurrah!

**Comment by trefis** [comment]
I just pushed a few commits which fix these problems.
Please tell me if you notice any other regression.

**Comment by bbc2** [comment]
Actually, it wasn't completely fixed before your new commits.  I noticed some time later that if the target was in the same file, vim would complain about the cursor trying to go out of bounds and a new empty buffer would be created.

Now, with your new commits, there isn't any problem when navigating within a buffer but I'm were we started, that is, it will no longer change buffers to show me a definition outside the current file.  And as of these commits, this also happens without `keep_locs`, it seems.

**Comment by trefis** [comment]
Ah indeed.
I completely broke vim (emacs is working fine though, maybe you should switch over).

**Comment by Khady** [comment]
There is still an issue in emacs. I have `foo.ml` that contains the declaration of `example`, and `foo.mli`. In `bar.ml`, I use `Foo.example`. If I try to locate `Foo`, it jumps on `foo.ml`. However, if I locate `example`, it jumps to `foo.mli`.

I don't have the issue if I don't compile with `-keep-locs`.

**Comment by Khady** [comment]
Will you include this fix in the next release? Even with the problem of `ml/mli` it helps.

**Comment by trefis** [comment]
Quick update to let you know that:
- this didn't make it in the 2.3 version of merlin
- it is still broken
- I haven't forgotten about it and plan to get back on it soon

**Comment by trefis** [comment]
I just rebased the branch and fixed the silly mistake present in the vim plugin.
It should work "fine" now.

As for @Khady's ml/mli problem I wasn't able to reproduce. (But the fact that you use 4.02.1+PIC shouldn't change anything)

**Comment by Khady** [comment]
https://github.com/Khady/merlin-keep-locs

I use 4.02.3+PIC and I can reproduce with vim and emacs:

- open `bar.ml`
- move to `example`
- `:MerlinLocate`
- it opens `foo.mli`

**Comment by trefis** [comment]
Ah, yes indeed.
I didn't notice an inconsistency because I configured my editor to always jump to mlis.

Here you notice that behavior because:
- when you locate `Foo.example` the location is in the environment, it comes from the cmi, and the locations in there refer to the .mli
- when you locate `Foo` there is no location in the environment, so we look for either `foo.ml` or `foo.mli` depending on your configuration.

**Comment by Khady** [comment]
If this is the expected behaviour, then it works for me.

**Comment by trefis** [comment]
The patches are now on master.
