### ISSUE TITLE
Release a binary version for use on Windows

### ISSUE THREAD

**Issue by romildo** [the-lambda-church/merlin#451]
I would like to use Emacs + Merlin on my functional programming classes. Please add  a binary release of Merlin for Windows.

**Comment by def-lkb** [comment]
Issue handled in private discussion.

An automated workflow for releasing windows binary is not yet ready but those can be made on a case-by-case basis.

**Comment by def-lkb** [comment]
Update: I just described a windows installer preview in #409 .
