### ISSUE TITLE
possible bug in nonrec type support

### ISSUE THREAD

**Issue by nilsbecker** [the-lambda-church/merlin#452]
i get merlin flagging an error on code that actually compiles fine. consider this:

    module Species = struct
      type id = int
      let id_counter = ref 0
      type t = { id: id; label: string; radius: float; d: float }
      let make ~radius ~d ~label =
        let id = !id_counter in incr id_counter;
        {id; radius; d; label}
      module Hashed = struct
        type nonrec t = t
        let hash s = Int.hash s.id
        let equal s s' = Int.equal s.id s'.id
      end
end

here the line `type nonrec t = t` is flagged as 'unbound type constructor nonrec' which seems like nonsense?

merlin should be at the current version..

**Comment by def-lkb** [comment]
Have you tried on current git version? It works as expected here.

**Comment by nilsbecker** [comment]
how can i install that easily? some opam pin magic?

**Comment by def-lkb** [comment]
Yes, this should do it:
```
opam pin add merlin https://github.com/the-lambda-church/merlin#prerelease
```

**Comment by nilsbecker** [comment]
hmm, no luck:

    [ERROR] The compilation of merlin failed at "./configure --prefix /Users/nbecker/.opam/4.02.3".

exit code 127, empty error log. weird. i force-uninstalled merlin before.

**Comment by nilsbecker** [comment]
reinstalling the 2.2 version works. the reported error is still there...

**Comment by def-lkb** [comment]
URL was wrong sorry:
```
opam pin add merlin https://github.com/the-lambda-church/merlin.git#prerelease
```

**Comment by nilsbecker** [comment]
ok, this does install and it seems to have fixed the issue! thanks.

**Comment by def-lkb** [comment]
Cool. You're welcome.
