### ISSUE TITLE
merlin fails on startup in merlin/send-command-async

### ISSUE THREAD

**Issue by jbulow** [the-lambda-church/merlin#457]
No matter what I type I get this or similar error in message buffer:

Error in merlin/send-command-async callback: (error "Command ((assoc) (context auto /Users/jonas/ocaml/test.ml) (query tell start at ((assoc) (line . 1) (col . 0)))) failed with error invalid arguments")
Error in merlin/send-command-async callback: (error "Command ((assoc) (context auto /Users/jonas/ocaml/test.ml) (query tell source-eof let x=3 in x+3;;
  
)) failed with error invalid arguments")

**Comment by def-lkb** [comment]
Yes, it happens if you are mixing emacs mode from git with binary from opam.
Either use the emacs mode provided by opam or binary from git.

For the latter:
```
opam pin add merlin https://github.com/the-lambda-church/merlin.git
```

**Comment by jbulow** [comment]
Running 
opam pin add merlin https://github.com/the-lambda-church/merlin.git 
outputs: (I'm new to OCaml and are just trying to set up an environment for learning)

#=== ERROR while installing merlin.2.2 ========================================#
# opam-version 1.2.2
# os           darwin
# command      make -j 1
# path         /Users/jonas/.opam/4.02.0/build/merlin.2.2
# compiler     4.02.0
# exit-code    2
# env-file     /Users/jonas/.opam/4.02.0/build/merlin.2.2/merlin-28197-a00279.env
# stdout-file  /Users/jonas/.opam/4.02.0/build/merlin.2.2/merlin-28197-a00279.out
# stderr-file  /Users/jonas/.opam/4.02.0/build/merlin.2.2/merlin-28197-a00279.err
### stdout ###
# /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.ocamlmakefile WITH_BIN_ANNOT="" WITH_DEBUG="" REALLY_QUIET=1 ocamlmerlin
### stderr ###
# File "src/ocaml/typing/typecore.ml", line 3032, characters 10-16:
# Error: This variant pattern is expected to have type
#          (a, b, c, d, e, f, g, h, i, j, k, l)
#          CamlinternalFormatBasics.fmtty_rel
#        The constructor Any_ty does not belong to type CamlinternalFormatBasics.fmtty_rel
# Hint: Did you mean Int_ty?
# make[2]: *** [src/ocaml/typing/typecore.cmx] Error 2
# make[1]: *** [native-code] Error 2
# make: *** [ocamlmerlin] Error 2

**Comment by def-lkb** [comment]
I recommend switching to a more recent version of OCaml, e.g. `opam switch 4.02.3`.
It is compatible with 4.02.0, with important bug fixes (and some internal changes that won't matter if you are a beginner).

**Comment by jbulow** [comment]
Switching to OCaml 4.02.3 solved the installation problem of merlin. 

I don't really understand why I got this problem. I just followed the official installation instructions. What did I miss? What do you mean when you say I'm missing emacs mode from git with binary from opam?

**Comment by jbulow** [comment]
..but now utop broke:

opam config exec utop -- -emacs
Fatal error: exception # opam-version    1.2.2
# os              darwin
opam: "execvp" failed on utop: No such file or directory

% utop
Fatal error: the file '/Users/jonas/.opam/system/bin/utop' is not a bytecode executable file

% which utop
/Users/jonas/.opam/system/bin/utop

% file /Users/jonas/.opam/system/bin/utop
/Users/jonas/.opam/system/bin/utop: a /opt/local/bin/ocamlrun script text executable

What is the correct way of upgrading the OCaml version without breaking everything else? I used the command you recommended.

**Comment by def-lkb** [comment]
Don't use the system switch, installer utop in the current one (`opam install utop`)

**Comment by jbulow** [comment]
What is the system switch? I used ```opam switch 4.02.3```

**Comment by def-lkb** [comment]
A switch is a separate installation of OCaml, either to have different versions in parallel, to maintain a separate set of packages, whatever...

The system switch is the one maintained by the system (e.g. package manager, brew, macports, ...) and not by opam.

Your version of utop was tied to system switch (as pointed out by the path in your error message: .opam/system), apparently conflicting with the recent installation of 4.02.3.

Dev tools are especially tied to a version of the compiler, it is better to install them in each switcj.

**Comment by def-lkb** [comment]
In what way is it still broken after reinstall?
Are you sure your shell is properly setup?

**Comment by def-lkb** [comment]
(If you don't mind, please share the output of `env` shell command)

**Comment by jbulow** [comment]
A simple "rehash" solved the problem. 

I really appreciate your help! It's quite hard to get into the OCaml ecosystem :-)

**Comment by gasche** [comment]
> I really appreciate your help! It's quite hard to get into the OCaml ecosystem :-)

You're not the only one coming to this conclusion, but unfortunately it's rather difficult to improve things -- we can only do it bits by bits and it requires a lot of small things to improve. One of the problem is tahat the switch mechanism is devilishly convenient for advanced users but rather impenetrable to adopters -- it's even much worse for people that are comfortable using their system but don't have much of a mental model of UNIX environments and their consequences.

**Comment by def-lkb** [comment]
As @gasche said.

And to reply to you earlier question: merlin comes in different parts. In your case, the binary (ocamlmerlin) and the emacs mode.
The protocol sometime changes, and so both have to keep in sync from time to time.
I would guess that you installed the merlin mode from melpa, which sadly targets the git master and is more recent than opam package (although a release is being prepared).

**Comment by gasche** [comment]
@def-lkb , would it be possible to embed versioning in the Merlin protocol to give a clear error message to users in this case?

**Comment by jbulow** [comment]
Ironically, I consider myself as quite used to UNIX-like system from having different kind of UNIX-systems as my primary platform of choice the last 20 years. :-)

It's hard to point on a single aspect of the OCaml ecosystem that makes it harder than other languages. In this case it was a combination of the "sorry state" of the package system in emacs ( http://blog.jorgenschaefer.de/2014/06/the-sorry-state-of-emacs-lisp-package.html ) and the somewhat obscure opam package system that did not play well together. On top of that I made it even harder by using a shell (tcsh) that need an explicit rescan when the PATH changes.

**Comment by gasche** [comment]
Apologies for being unclear and possibly irritating: I wasn't assuming that you were in that category (in fact it's quite clear from the quality of your failure reports that you aren't), but thinking of other people I've helped that had even more trouble.

**Comment by ethanluoyc** [comment]
Hi I am coming from the Spacemacs community and I encountered the same problem again with the Ocaml layer.

I installed my ocaml and OPAM with Homebrew and I also followed the solution above and installed a switch of the OCaml and pinned a version of the Merlin as suggested. Still I encountered the same problem.

The error message is included below:

> Error in merlin/send-command-async callback: (error "Command ((assoc) (context auto /Users/Ethan/dev/playground/ocaml/counter.ml) (query tell start at ((assoc) (line . 1) (col . 0)))) failed with error invalid arguments")

Any idea how this might be the case?

**Comment by tizoc** [comment]
@ethanluoyc I just had this same issue, turns out spacemacs' had its own copy of merlin in its elpa directory, which is what was being loaded instead of the one installed by opam.

Upgrading it should fix the issue: use the `[Update Packages]` "button" found in spacemacs' starting page or if you don't want to have everything updated do like I did and delete `~/.emacs.d/elpa/merlin-*` and restart emacs).

The ocaml layer is supposed to use the version installed by opam (https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/ocaml/funcs.el#L20) but it is not working correctly (the elpa version is being put first in the `load-path`).

**Comment by ethanluoyc** [comment]
Yes, after a reinstall the problem seems to go away.





On Thu, Jul 7, 2016 at 5:19 AM +0800, "tizoc" <notifications@github.com> wrote:












@ethanluoyc I just had this same issue, turns out spacemacs' had its own copy of merlin in its elpa directory, which is what was being loaded instead of the one installed by opam.



Upgrading it should fix the issue: use the [Update Packages] "button" found in spacemacs' starting page or if you don't want to have everything updated do like I did and delete ~/.emacs.d/elpa/merlin-* and restart emacs).



The ocaml layer is supposed to use the version installed by opam (https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/ocaml/funcs.el#L20) but it is not working correctly (the elpa version is being put first in the load-path).

**Comment by xguerin** [comment]
When pinning `merlin` in opam, running `emacs -Q` and loading both `tuareg` and `merlin`, I get the same error, except "failed with error nil". I am using `emacs` 24.5.1. My compiler version is 4.03.

**Comment by zbroyar** [comment]
Hi,

Just met almost the same problem. I have just one merlin.el and it's correctly placed in ~/.opam/4.03.0/share/emacs/site-lisp/merlin.el

Ubuntu 16.04, Emacs 24.5.1, Merlin 2.5.3

% cat .merlin
S .
B ./_build
PKG atdgen yojson biniou curl pcre unix cryptokit netclient
PKG smtp ssl ocplib-endian nocrypto pgocaml pgocaml.syntax
PKG lacaml ppx_deriving pgocaml.ppx mybuild deriving
%

Error in merlin/send-command-async callback: (error "Command ((assoc) (document auto /home/z/proj/test/test.ml) (query protocol version 3)) failed with error nil")
Error in merlin/send-command-async callback: (error "Command ((assoc) (document auto /home/nick/proj/imitation/depth.ml) (query tell start end open Local <full module body here> )) failed with error nil")

Please, help

**Comment by tizoc** [comment]
@zbroyar are you using spacemacs? if thats the case, try deleting the merlin directory in your emacs' .elpa directory and have spacemacs reinstall it again. See https://github.com/syl20bnr/spacemacs/issues/6521

**Comment by zbroyar** [comment]
@tizoc nope, it's the usual emacs installed by "apt-get install"

**Comment by let-def** [comment]
What is the output of `merlin-version`?

**Comment by zbroyar** [comment]
@let-def it's nil

**Comment by let-def** [comment]
What about M-x shell-command which ocamlmerlin ?

**Comment by zbroyar** [comment]
Right now I see ocamlmerlin started from correct location.

**Comment by zbroyar** [comment]
But shell-command which ocamlmerlin gives me "file not found"

**Comment by let-def** [comment]
Probably your `PATH` is just not setup. You can set it explicitly with `M-x customize-variable merlin-command`.

**Comment by zbroyar** [comment]
@let-def thanks for your help and time. The problem was in my .emacs: somehow I put there second setenv command with wrong parameters.
