### ISSUE TITLE
Cannot setup flycheck

### ISSUE THREAD

**Issue by caisah** [the-lambda-church/merlin#458]
Hi, I'm trying to configure Emacs for OCaml for the first time. I have installed `merlin` via `opam` and the corresponding package from `melpa`. Now I'm trying to configure `flycheck`.

In my `init` file I have something like:

`(with-eval-after-load 'merlin
  ;; Disable Merlin's own error checking
  (setq merlin-error-after-save nil)

  ;; Enable Flycheck checker
  (flycheck-ocaml-setup))

(require 'merlin)
(add-hook 'tuareg-mode-hook 'merlin-mode)`

But I get: 
`Error in merlin/send-command-async callback: (error "Command ((assoc) (context auto /home/caisah/Documents/courses/functional-programming/00/test.ml) (query errors)) failed with error invalid arguments")`.

What might be the problem here? Am I doing something wrong? Is this a `flycheck` problem?
Thanks!

**Comment by def-lkb** [comment]
See #457 .
Melpa is not in sync with opam version. The opam version will be updated during the week or next one...
In the meantime, you can either use the opam installed mode files, or switch to git versoin.

**Comment by caisah** [comment]
Thanks for the quick reply.

**Comment by def-lkb** [comment]
Did you manage to fix the setup?

**Comment by caisah** [comment]
Not yet, but I'll manually install the `.el` files and that should do it, right  :relaxed:
