### ISSUE TITLE
emacs from scratch : tuareg, ocp-indent ?

### ISSUE THREAD

**Issue by william3** [the-lambda-church/merlin#463]
Hello, it is maybe beyond the scope of your project, but I see Merlin as some kind of "ultimate" tool to use if I develop ocaml with emacs. However, it is not explained how this interact with tuareg and ocp-indent. Should I install all of them ? 

There is a line later on during installation that mentions tuareg, and that is where I understood that I should keep it. I first thought : "merlin has maybe nice features, but without syntax hilighting this looks really bad, I might just keep tuareg".
Clearly you should mention in the beginning of the section "emacs from scratch" how to really install emacs from scratch, and thus pointing to tuareg and maybe ocp-indent. 

Best regards

**Comment by agarwal** [comment]
Related to ocaml/tuareg#70.

**Comment by william3** [comment]
actually, in the first page with the README.md, tuareg is mentionned in a part called "Emacs interface". 
But at the beginning of the README.md I was invited not to read it, because it says "this is only for installation from sources. Please see the wiki for use in your environment"
Maybe the documentation would need some reorganisation of parts ...

**Comment by let-def** [comment]
Thanks, updated. I will try to produce a more consistent documentation file (on top of wiki).
