### ISSUE TITLE
merlin 2.3 breaks auto-complete key bindings with emacs

### ISSUE THREAD

**Issue by samoht** [the-lambda-church/merlin#464]
I have the following in my `.emacs`:
```
(global-set-key [backtab] 'auto-complete)
```

This worked well with merlin 2.2. This doesn't work anymore with merlin 2.3, I get:

```
Symbol's function definition is void: auto-complete
```

when I press SHIFT+TAB.

**Comment by def-lkb** [comment]
Probably you should `(require 'auto-complete)`?

**Comment by samoht** [comment]
Ha this indeed works now, thanks! Now sure why this was working fine with previous versions of merlin

**Comment by def-lkb** [comment]
In previous versions the mode directly made use of auto-complete, ignoring the feature if load failed.

Now it checks if auto-complete is enabled before, not trying to force load it. This seemed more respectful of emacs customs :).
