### ISSUE TITLE
merlin-try-completion is void on version 2.3 with emacs

### ISSUE THREAD

**Issue by correnson** [the-lambda-church/merlin#465]
On Mac/OS, using Melpa auto-complete on Emacs with the recommended .emacs config provided by opam install merlin.
 - Merlin 2.2 : auto-complete works like a charm
 - Merlin 2.3 : auto-complete is broken with message 'merlin-try-completion is void'

Both Carbon Emacs and Homebrew Emacs are affected.

**Comment by def-lkb** [comment]
Merlin now tries to integrate with "normal" auto-complete infrastructure.
`merlin-try-completion` has been removed and `M-x auto-complete` should do the work.
Is it working for you?

Note that you might need to `(require 'auto-complete)` in your `.emacs`.

**Comment by correnson** [comment]
Perfect! Thanks for the tip. Package `auto-complete` seems to be automatically enabled in my config.
This port should have been mentioned in the opam doc, indeed... but so great is Merlin!
