### ISSUE TITLE
How to let merlin find the library and stop complaining?

### ISSUE THREAD

**Issue by MassD** [the-lambda-church/merlin#467]
I successfully installed merlin and it works in emacs.

I then installed the lib `camlimages` using opam.

And try to `open Camlimages` in my `.ml`, and merlin complained no such module.

Do I need to do anything to let merlin find the lib?

**Comment by gasche** [comment]
You should have a `.merlin` file at the root of your project that describes the packages Merlin needs to lead, see [the documentation on project configuration](https://github.com/the-lambda-church/merlin/wiki/project-configuration).

**Comment by trefis** [comment]
https://github.com/the-lambda-church/merlin/wiki/emacs-from-scratch#using-libraries

Le ven. 13 nov. 2015 16:30, Jackson Tale <notifications@github.com> a
écrit :

**Comment by MassD** [comment]
Thanks @gasche @trefis
