### ISSUE TITLE
Type definitions do not support single `@` attributes at the top level.

### ISSUE THREAD

**Issue by tizoc** [the-lambda-church/merlin#471]
Merlin complains about attributes (with a single '@') placed at the top level of type definitions.

These work:

```ocaml
type t1 = int [@@attribute] (* double @ *)
type t2 = {
  i : int [@attribute]
}
```

These don't:

```ocaml
type t3 = int [@attribute]
type t4 = { i : int } [@attribute]
```

The error message is:

```
Syntax error inside `type', expecting `='
```

**Comment by trefis** [comment]
IIRC `t4` is not accepted by ocaml, as for `t3` this is indeed a bug.

**Comment by tizoc** [comment]
You are right, `t4` is invalid.

**Comment by def-lkb** [comment]
The grammar is not yet 100% compliant with 4.02.3 since it changed a lot between 4.02.2 and 4.02.3.
Porting the new grammar will take more time.

**Comment by tizoc** [comment]
Just updated merlin and it is working perfectly now, thanks!
