### ISSUE TITLE
Which version of Menhir is required for experimental-refactor branch?

### ISSUE THREAD

**Issue by jordwalke** [the-lambda-church/merlin#479]
Is there some way that this should be specified as a dependency in the opam file? I tried a few different versions of the OPAM Menhir library and neither of them would compile successfully with that branch.

**Comment by jordwalke** [comment]
Some specific errors I'm trying to resolve:

`make` complains about an unbound module: `MenhirLib.IncrementalEngine.INSPECT_AND_DEBUG`.

I'm having trouble finding the version of Menhir that has this signature.

**Comment by def-lkb** [comment]
Dependencies inlined in experimental branch.
