### ISSUE TITLE
merlin-locate fails on me

### ISSUE THREAD

**Issue by UnixJunkie** [the-lambda-church/merlin#481]
Not in environment 'x'
How to troubleshoot?
This is mostly the only merlin feature I need to use ...

**Comment by UnixJunkie** [comment]
It only works when the definition is in the same file.
Not very useful since I want to use merlin in big projects (not written by me so I don't know where things are defined).

**Comment by trefis** [comment]
https://github.com/the-lambda-church/merlin/wiki/vim-from-scratch#source-browsing

**Comment by UnixJunkie** [comment]
OK, the .merlin file was completely outdated, sorry for the noise.
