### ISSUE TITLE
Compilation fails at dot_merlin.ml

### ISSUE THREAD

**Issue by pococito** [the-lambda-church/merlin#482]
Compilation fails with below errors:

```
pawel@paweldebian:merlin-2.3.1$ uname -a
Linux paweldebian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux
pawel@paweldebian:merlin-2.3.1$ ocaml -version
The OCaml toplevel, version 4.01.0
pawel@paweldebian:merlin-2.3.1$ ./configure 
Merlin configuration
--------------------
Found findlib	GOOD
Found yojson	GOOD

System config:
  OCaml ABI version: OCaml 4.01.0
  Native code: true

Will install:
  ocamlmerlin binary in: /usr/local/bin
  vim mode in: /usr/local/share/ocamlmerlin/vim

To customize directories, use:
  ./configure [--prefix <dir>] [--bindir <dir>] [--sharedir <dir>] [--vimdir <vimdir>] [--with-vimbufsync | --without-vimbufsync]

For more informations rerun with --help.
Now, type 'make' to compile then 'make install'.
pawel@paweldebian:merlin-2.3.1$ make
make -f Makefile.ocamlmakefile WITH_BIN_ANNOT="" WITH_DEBUG="" REALLY_QUIET=1 ocamlmerlin
make[1]: Entering directory '/home/pawel/Downloads/merlin-2.3.1'
make[2]: Entering directory '/home/pawel/Downloads/merlin-2.3.1'
File "src/kernel/dot_merlin.ml", line 297, characters 60-64:
Error: The function applied to this argument has type string -> string
This argument cannot be applied with label ~explicit**
OCamlMakefile:1076: recipe for target 'src/kernel/dot_merlin.cmx' failed
make[2]: *** [src/kernel/dot_merlin.cmx] Error 2
make[2]: Leaving directory '/home/pawel/Downloads/merlin-2.3.1'
OCamlMakefile:777: recipe for target 'native-code' failed
make[1]: *** [native-code] Error 2
make[1]: Leaving directory '/home/pawel/Downloads/merlin-2.3.1'
Makefile:57: recipe for target 'ocamlmerlin' failed
make: *** [ocamlmerlin] Error 2
```

**Comment by def-lkb** [comment]
The findlib version bundled by Debian is too old.
Is it possible for you to switch to an opam managed ocaml?

Otherwise, I can send you a patch as soon as I have access to a computer, that is in ~30 min.

**Comment by pococito** [comment]
Yup, actually I did migrate fully to opam just yesterday but it broke down a long and complex project from before opam times, so had to revert back to debian's stable stuff. All worked there great so far with all essential ocaml packages available. I'd appreciate the patch, no hurry. Thx for the quick reply

**Comment by def-lkb** [comment]
Just removing the "~explicit" argument should do it.
As far as I recall, the behavior should stay correct with this version of findlib. I have no time to test yet though.

**Comment by pococito** [comment]
Done it and compilation finished ok now. Thx for the tip. What is the easiest way to verify if the binary works correctly? I want to use it in the [Atom editor](atom.io), the [nuclide package.](https://atom.io/packages/nuclide-ocaml)

**Comment by def-lkb** [comment]
Just launching the binary should be ok: it will test for Findlib presence which is the main environment-sensitive thing.
Then you can check: 
- version string: `echo '["version"]' | ocamlmerlin`
- errors of empty file: `echo '["errors"] | ocamlmerlin`.

Finally, you can enumerate findlib packages in your installation:
```
$ ocamlmerlin
["find","list"]
["return",["findlib","str","compiler-libs","compiler-libs.common","compilerlibs.bytecomp","compilerlibs.optcomp","compilerlibs.toplevel","threads","threads.vm","threads.posix","bigarray","num","num.core","biniou","unix","easyformat","graphics","dynlink","numtop","bytes","ocamlbuild","cppo_ocamlbuild","yojson","yojson.biniou","stdlib"]]
```

If all of this succeeds with non-0 exit code and with sensible list of packages, you are good.

## Detecting and fixing wrong setup (useful if you are implementor of nuclide mode)

If you take care of the dependency on Findlib and standard library, the binary should even be relocatable.
Launching without findlib:
```
$ ocamlmerlin
Fatal error: exception Failure("Config file not found - ...")
# Findlib found at compile-time was removed, disable findlib
$ OCAMLFIND_CONF=/dev/null ocamlmerlin
["find","list"]
["return",[]]
# No library anymore. You could have set a correct path to an findlib.conf file to use another installation
```

Finally, if you use multiple ocaml switches (but for the same version of OCaml), you may want to choose a different stdlib ("pervasives" module) by setting OCAMLLIB environment variable.

Checking for wrong standard library:
```
$ OCAMLLIB= ~/Work/merlin/ocamlmerlin 
["errors"]
["error",{"type":"type","start":{"line":1,"col":-1},"end":{"line":1,"col":-1},"valid":true,"message":"Error: Unbound module Pervasives"}]
```

Message for a wrong version of OCaml:
```
Error: /my-installation/pervasives.cmi is not a compiled interface for this version of OCaml. It seems to be for an older version of OCaml.
```

Message when having dependencies built for a different switch (you built a project, you changed switch, you loaded the project in merlin: files are incompatible):
```
Error: The files /home/def/.opam/4.02.3/lib/ocaml/pervasives.cmi and /home/def/Work/grenier/orderme/order_list.cmi make inconsistent assumptions over interface CamlinternalFormatBasics
```

**Comment by pococito** [comment]
Thanks for all the test cases. I checked, and it works. Now also in the Atom editor. Hence closing the issue.

Btw - I made a [wiki page about merlin in Atom](https://github.com/the-lambda-church/merlin/wiki/atom-from-scratch). I also have some screen snaps I wanted to paste in, but don't see an upload option...

**Comment by def-lkb** [comment]
You can send them to me by email, I'll figure a way to host them.

**Comment by pococito** [comment]
Sure, but there's no email listed on your profile :)

**Comment by def-lkb** [comment]
:), frederic.bour (_) lakaban.net

**Comment by slyfr** [comment]
Merlin was not working for me with ocaml 4.02.2.  I switched with OPAM to coaml 4.04.0 and now I get the error Merlin failed with error: "Error: ~/.opam/4.04.0/lib/ocaml/pervasives.cmi
is not a compiled interface for this version of OCaml.
It seems to be for a newer version of OCaml."
I do not see how to make things work.

**Comment by let-def** [comment]
What do you mean by "was not working for me with ocaml 4.02.2"?

There is no support for 4.04 released yet. 4.02.2 is supported (though 4.02.3 is preferable).

**Comment by slyfr** [comment]
I had some behavior similar to what is reported here https://github.com/the-lambda-church/merlin/issues/457

I actually went to ocaml 4.03.0 and everything is fine now.
