### ISSUE TITLE
Merlin cannot find findlib package

### ISSUE THREAD

**Issue by dariusf** [the-lambda-church/merlin#483]
I'm trying to create a package with a runtime library as well as a ppx preprocessor. I've gotten it to install properly such that `ocamlbuild -package $(PACKAGE)` picks it up and can build a project. Merlin (via Emacs) can't find it though.

.merlin file:

```
B _build/**
PKG $(PACKAGE)
```

`ocamlfind query $(PACKAGE)` returns `~/.opam/system/lib/$(PACKAGE)`, which contains a cma file and a cmi file (for the runtime library) and a `native` file (the ppx preprocessor), in addition to the usual opam files.

Merlin works fine for other findlib libraries.

Do I need to do anything else for Merlin to be able to find the package?

Edit: forgot to mention that it's installed via `opam pin`, since it's still in development.

**Comment by def-lkb** [comment]
There is nothing special to do, it should just work.
As long as Merlin is using the same ocamlfind repository of course.

You can force one by setting `OCAMLFIND_CONF=~/.opam/system/lib/findlib.conf` in the environment (check that the file exists to be sure, I might be remembering the path wrong).

**Comment by dariusf** [comment]
Thanks for the suggestions! I've checked and it seems to be the same repository.

I suspect it's the ppx preprocessor that's causing the problem. With `PKG $(PACKAGE)` in `.merlin`, Merlin also reports a number of errors in unrelated source code. Removing it resolves the errors.

Is there a way to simulate how Merlin invokes the ppx preprocessor, so I can see what exactly is wrong?

**Comment by def-lkb** [comment]
Can you tell which ppx is involved and what the errors are?

Usage of PPX in Merlin follows usage of ppx in the toplevel, which differs from usage in the normal compiler. This is known to break sedlex for instance.

Next version should follow compiler behavior.

**Comment by dariusf** [comment]
I've narrowed the problem down to a library called [TyPPX](https://bitbucket.org/camlspotter/typpx), which is an implementation of [this idea](https://bitbucket.org/camlspotter/compiler-libs-hack).

There's a minimal repro [here](https://github.com/dariusf/typpx_merlin). I've also emailed camlspotter but haven't gotten a response yet.

The first post is a little inaccurate now. Here's a summary of the problem:

- We have a ppx that depends on TyPPX. It is packaged via ocamlfind.
- We have a project that depends on the above package (referenced via `PKG` in `.merlin`)

When opening files in the project, we get those strange errors. I tried it outside Emacs to the same effect.

The TyPPX readme mentions that it doesn't work with the REPL, which may be relevant.

**Comment by camlspotter** [comment]
> Usage of PPX in Merlin follows usage of ppx in the toplevel, which differs from usage in the normal compiler. This is known to break sedlex for instance.

FYI, if Merlin restarts PPX process for each toplevel phrase, it will have problems with TyPPX; it highly depends on the states which should be kept between toplevel phrases.

**Comment by def-lkb** [comment]
Yes merlin does that. Although it takes care to share the state cookies between invocation.

The next release will reinvoke the PPX with the full file each time.

**Comment by let-def** [comment]
Merlin master invokes PPX like the compiler, it should be fine now.
