### ISSUE TITLE
Prefer emitting "tail call" to "tail position"

### ISSUE THREAD

**Issue by infinity0** [the-lambda-church/merlin#487]
Consider:

~~~~
let rec lrec n l =
  if l = [] then n
  else lrec (n+1) (List.tl l)
~~~~

If I put my cursor between `else` and `lrec` and press `C-c t` (in emacs), merlin emits `int (* tail position *)`. However, if I have the following equivalent code:

~~~~
let rec lrec n l =
  if l = [] then n
  else
    let x = 3 in
    lrec (n+1) (List.tl l)
~~~~

and I put my cursor between `in` and `lrec` and press `C-c t`, merlin emits `int (* tail call *)`.

Merlin should emit this even in the former case, since `tail call` is stricter than `tail position` and gives the reader more information.

**Comment by infinity0** [comment]
Merlin seems to do the right thing for `match` clauses, FWIW:

~~~~
let rec lrec n l = match l with
  | [] ->#n
  | _ ->$lrec (n+1) (List.tl l)
~~~~

Placing the cursor at # and $ gives you tail position and tail call respectively.

**Comment by trefis** [comment]
> Merlin should emit this even in the former case, since `tail call` is stricter than `tail position` and gives the reader more information.

Except that in the first case the whole if expression is considered, not the function call, so `tail position`  seems more correct?

As for why the whole `if` is considered instead of just the `else` branch I can't say. @def-lkb ?

**Comment by def-lkb** [comment]
There is a hack in Merlin parser to generate larger than normal locations for `match` and `let in`.

Strictly speaking, the correct behavior is the one for `if`. The cursor is outside the application sub-expression, thus the first expression containing the cursor is the `if`.
Think of the location where a type error should be reported.

That explains the behavior. The fix will be to add more locations for all keywords delimited constructs I guess.

**Comment by infinity0** [comment]
In case anyone is looking for a workaround, it looks like `C-c C-f` works in tuareg (it outputs one of "stack call", "tail call" or "Point is not within a function call"), but only after you compile the file.
