### ISSUE TITLE
Incorrect warning line number

### ISSUE THREAD

**Issue by rgrinberg** [the-lambda-church/merlin#490]
I'm not 100% sure this is merlin's fault, could it be ppx_tools.metquot's?

Steps to reproduce:

1) Open ppx_deriving's source:

https://github.com/rgrinberg/ppx_deriving/blob/master/src_plugins/ppx_deriving_eq.ml#L90

2) Delete the highlighted line. (`:90d` in vim)

3) save

4) Observe warning on line 42:

```
src_plugins/ppx_deriving_eq.ml|42 warning| Warning 8: this pattern-matching is not exhaustive. Here is an example of a value that is not matched: (_, {ptyp_desc=(Ptyp_any|Ptyp_var _|Ptyp_arrow (_, _, _)|Ptyp_tuple _| Ptyp_object (_, _)|Ptyp_class (_, _)|Ptyp_alias (_, _)| Ptyp_variant (_, _, _)|Ptyp_poly (_, _)|Ptyp_package _| Ptyp_extension _)}) 
```

Expected result:

The same warning but on the correct line (line 50 in this case)

**Comment by let-def** [comment]
I am trying to reproduce this bug. The link is outdated, do you still have the source?

**Comment by rgrinberg** [comment]
Unfortunately not. Cpp preprocessing has been added to that source file and I'm not sure commit I've worked on when I found this bug.
