### ISSUE TITLE
Discussion: providing a standard alone merlin distribution

### ISSUE THREAD

**Issue by bobzhang** [the-lambda-church/merlin#492]
One major thing which prevents merlin being adopted is that you have to pin to  a specific compiler, this is not a big issue for home projects or OCaml shop like Janestreet :-) . But people in general don't have much freedom to choose their compiler version when working in a large organization. Since the source language of ocaml does not change that much(and mostly backward compatible), is it possible to provide a stand alone merlin distribution, so it works out of box no matter what compiler I use in my own build system?
Thanks -- Hongbo

**Comment by let-def** [comment]
Merlin only depends on a compiler version. This is more general than a specific compiler.

To relocate a merlin binary, you have to provide the location of standard library of the other compiler & the findlib conf file (`CAMLLIB` & `OCAMLFIND_CONF` environment variables).

This behavior will be documented and simplified in next version.
