### ISSUE TITLE
Merlin doesn't build

### ISSUE THREAD

**Issue by 0xABAB** [the-lambda-church/merlin#494]
I think you didn't document your dependencies correctly and additionally sturgeon doesn't build from source.

`ocamlfind: Package `sturgeon' not found`

**Comment by ihodes** [comment]
I am also having this problem, and trying to opam pin/install sturgeon (and then grenier) from source didn't work out.

**Comment by def-lkb** [comment]
The sturgeon package is used for debugging merlin, it is useless for the end user.
However, I made it mandatory in the git version, as this was mainly intended for merlin developers.

I pushed a temporary fix to disable the need for sturgeon. Later I will make it a configure time option.
Sorry for the hassle, the latest git should build without it (but 4.02.x only, no support for 4.03.0, and syntax errors are not reported right now).

**Comment by ihodes** [comment]
Good to know, I'll give it a try. Thanks for the help! Trying to get into hacking on merlin a bit.
