### ISSUE TITLE
4.03, merlin complains about indexing operators in emacs

### ISSUE THREAD

**Issue by dbuenzli** [the-lambda-church/merlin#496]
E.g. in the following program: 
```
let () = ignore (Sys.argv.(0))
```
It highlights the `.(` and says `Error: Unbound value .()`. The same program is fine in 4.02.3.

**Comment by def-lkb** [comment]
Support for 4.03 is broken. No time to fix that this week.

**Comment by dbuenzli** [comment]
Actually it's not too bad.

**Comment by let-def** [comment]
Fixed in master.
