### ISSUE TITLE
emacs merlin cannot be started

### ISSUE THREAD

**Issue by yunxing** [the-lambda-church/merlin#498]
I'm getting issues starting merlin since the option -protocol sexp is not recognizable anymore (See the image below). 
![image](https://cloud.githubusercontent.com/assets/1017689/13654144/241c20b2-e60b-11e5-841d-9d361cb277c5.png)

Looks like this is related to [this diff](https://github.com/the-lambda-church/merlin/commit/7c897dae1b5abd2176e2e881bc451eee8fef28c8) where Main_args.flags is not passed to Arg.parse anymore.

**Comment by def-lkb** [comment]
Sorry for the inconvenience.

**Comment by yunxing** [comment]
@def-lkb Thanks!
