### ISSUE TITLE
Can not install merlin.2.3.1 via opam on cygwin platform

### ISSUE THREAD

**Issue by pela9** [the-lambda-church/merlin#502]
merlin version 2.3 installs ok with opam on cygwin. With version 2.3.1 I get the following message from opam:

genovese[~]$ opam install -b -d merlin
The following actions will be performed:
  ∗  install merlin 2.3.1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[merlin] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] Installation of merlin.2.3.1 failed

#=== ERROR while installing merlin.2.3.1 ======================================#
Some files in ~/.opam/4.02.3/install/merlin.install couldn't be installed:
  - /home/pela/.opam/4.02.3/build/merlin.2.3.1/ocamlmerlin to /home/pela/.opam/4.02.3/bin

**Comment by let-def** [comment]
Sorry for taking such a long time to answer. Can you check if this problem still occur on latest version?

**Comment by TheHaricover** [comment]
Hi !

I have issues installing merlin with opam on cygwin too. It's not exactly the same issue :

>$ opam install merlin
>The following actions will be performed:
>  *  install cppo        1.4.0                  [required by yojson]
>  *  install easy-format 1.2.0                  [required by yojson]
>  *  install biniou      1.0.6                  [required by yojson]
>  *  install yojson      1.3.3                  [required by merlin]
>  *  install merlin      2.5.3
>===== *  5 =====
>Do you want to continue ? [Y/n]
>
>=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
>[easy-format.1.2.0] https://github.com/mjambon/easy-format/archive/v1.2.0.tar.gz downloaded
>[biniou.1.0.6] https://github.com/mjambon/biniou/archive/v1.0.6.tar.gz downloaded
>[cppo.1.4.0] https://github.com/mjambon/cppo/archive/v1.4.0.tar.gz downloaded
>[yojson.1.3.3] https://github.com/mjambon/yojson/archive/v1.3.3.tar.gz downloaded
>[merlin.2.5.3] https://github.com/the-lambda-church/merlin/archive/v2.5.3.tar.gz downloaded
>
>=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
>[ERROR] The compilation of easy-format failed at "make".
>[ERROR] The compilation of cppo failed at "make".
>
>=== ERROR while compiling easy-format.1.2.0 ==================================#

>  opam-version 1.3.0~dev2 (d4f7e01216dbb44af4e7cc6539a1b0afa9be9d2c)
>  os           win32
>  command      bash -c make
>  path         C:\cygwin64\home\Romain\.opam\system\build\easy-format.1.2.0
>  exit-code    2
>  env-file     C:\cygwin64\home\Romain\.opam\system\build\easy-format.1.2.0\easy-format-1596-335865.env
>  stdout-file  C:\cygwin64\home\Romain\.opam\system\build\easy-format.1.2.0\easy-format-1596-335865.out
>  stderr-file  C:\cygwin64\home\Romain\.opam\system\build\easy-format.1.2.0\easy-format-1596-335865.err
> ### stdout ###
>  ocamlfind ocamlc -c easy_format.mli
> ### stderr ###
>  ocamlfind: C:OCamlib\ld.conf: No such file or directory
>  ocamlfind: C:OCamlib\ld.conf: No such file or directory
>  ocamlfind: C:OCamlib\ld.conf: No such file or directory
>  make: *** [Makefile:16: all] Error 2
> 
> 
> === ERROR while compiling cppo.1.4.0 =========================================
>  opam-version 1.3.0~dev2 (d4f7e01216dbb44af4e7cc6539a1b0afa9be9d2c)
>  os           win32
>  command      bash -c make
>  path         C:\cygwin64\home\Romain\.opam\system\build\cppo.1.4.0
>  exit-code    2
>  env-file     C:\cygwin64\home\Romain\.opam\system\build\cppo.1.4.0\cppo-1596-d8a4ae.env
>  stdout-file  C:\cygwin64\home\Romain\.opam\system\build\cppo.1.4.0\cppo-1596-d8a4ae.out
>  stderr-file  C:\cygwin64\home\Romain\.opam\system\build\cppo.1.4.0\cppo-1596-d8a4ae.err
> ### stdout ###
>  echo 'let cppo_version = "1.4.0"' > cppo_version.ml
>  ocamlyacc cppo_parser.mly
>  ocamllex cppo_lexer.mll
>  368 states, 13139 transitions, table size 54764 bytes
>  3754 additional bytes used for bindings
>  ocamlopt -o cppo.exe -dtypes unix.cmxa str.cmxa cppo_version.ml cppo_types.ml cppo_parser.mli cppo_parser.ml cppo_lexer.ml cppo_command.ml cppo_eval.ml cppo_main.ml
>  cd ocamlbuild_plugin && ocamlbuild -use-ocamlfind ocamlbuild_cppo.cma ocamlbuild_cppo.cmxa ocamlbuild_cppo.a
>  mkdir 'C:\cygwin64\home\Romain\.opam\system\build\cppo.1.4.0\ocamlbuild_plugin\_build'
>  ''ocamlfind ocamldep -package ocamlbuild -modules ocamlbuild_cppo.mli > ocamlbuild_cppo.mli.depends
> ### stderr ###
>  ocamlfind: C:OCamlib\ld.conf: No such file or directory
>  make: *** [Makefile:74: ocamlbuild] Error 2
> 
> 
> 
> =-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> The following actions were aborted
>   *  install biniou 1.0.6
>   *  install merlin 2.5.3
>   *  install yojson 1.3.3
> The following actions failed
>   λ  build cppo        1.4.0
>   λ  build easy-format 1.2.0
> No changes have been performed

It seems that when the 'make' is made, the given path lose his '\'. So instead of "C:\OCaml\lib\ld.conf" the path become "C:OCamlib\ld.conf".
I don't know how to pass through this issue as it's all automatic, I can't make my own pass. I mean, when I paste "C:\OCaml\lib\ld.conf" in cygwin, it become "/cygdrive/c/OCaml/lib/ld.conf". But when the path is put on the terminal through another way than the paste, it don't work.

**Comment by let-def** [comment]
Note that the package that is failing is [cppo](https://github.com/mjambon/cppo), not Merlin.

Which opam distribution are you using? I was told http://fdopen.github.io/opam-repository-mingw/installation/ works well for Windows user.

**Comment by TheHaricover** [comment]
Yeah you're right, my mistake.

I'm reinstalling opam right now, because I saw another issue which lead me on [http://fdopen.github.io/opam-repository-mingw/installation/ ](http://fdopen.github.io/opam-repository-mingw/installation/). So I'll try with this and tell you.

**Comment by TheHaricover** [comment]
It worked very well. Thank you !
