### ISSUE TITLE
Cannot (clean) master

### ISSUE THREAD

**Issue by jordwalke** [the-lambda-church/merlin#503]
I have done `make clean`, then `./configure` and I still get the following errors (when I hadn't before):

```
                                                                                              ^
1 warning generated.
findlib: [WARNING] Interface pparse.cmi occurs in several directories: src/ocaml_aux, src/ocaml/utils
File "src/ocaml_aux/pparse.ml", line 1:
Error: The files src/ocaml/parsing/location.cmi
       and src/ocaml/utils/pparse.cmi make inconsistent assumptions
       over interface Warnings
make[2]: *** [src/ocaml_aux/pparse.cmx] Error 2
make[1]: *** [native-code] Error 2
make: *** [debug] Error 2

```

If I checkout a fresh clone of `merlin`, then I can correctly build `merlin`.

**Comment by def-lkb** [comment]
Yes you just have some leftovers from a different version.

The build system only remove files belonging to the current version, so in theory you should clean before checking out. This is not satisfying.

What about a "sanitize tactic" removing all *.cm* from src?
Please check that `find src/ -name '*.cm*' -delete` works as expected with BSD find (on OSX).

**Comment by jordwalke** [comment]
> The build system only remove files belonging to the current version, so in theory you should clean before checking out. This is not satisfying.

Makes sense, thanks!
