### ISSUE TITLE
FLG -pp not recognized

### ISSUE THREAD

**Issue by jordwalke** [the-lambda-church/merlin#505]
I tried to add the following to my `.merlin` file, and it is not recognized:

```
FLG -pp mypreprocessor_binary
I supposed I'll make another issue for it.
```

The only way to get this to work, is to start up the binary with `-pp`, but that's unfortunate because then the entire process uses the preprocessor, when you really only want it scoped to that project.

**Comment by let-def** [comment]
Now that there is proper support for external readers, it was decided not to further support -pp.
The flag will be removed in next version.
