### ISSUE TITLE
Emacs: merlin-locate does not switch files

### ISSUE THREAD

**Issue by thranur** [the-lambda-church/merlin#506]
I'm having a very specific issue, which must come from my own installation, but because I cannot find the cause, I'm asking here whether someone has already seen it and found a fix.

Since I've switched to the Merlin package in OPAM some time ago, I am no longer able to make `merlin-locate` work reliably when the definition is in another file:

- If I am in a file `a.ml`, within an expression `B.f`, and I put my cursor on the `B`, then `C-c C-l` (`merlin-locate`) takes me to the beginning of file `b.ml`, as expected.
- However, if I put the cursor on the function name (`f`), then do `merlin-locate`, it jumps to an apparently nonsensical location in `a.ml` itself, without ever showing `b.ml`.

This had always worked for me in the past.

I must have misconfigured something since then, but I cannot identify the cause.

I used to compile and use my own Merlin from the Git clone (version 2.1 I think), but lately I changed to OPAM's. I tried with all available versions that are compatible with OCaml 4.02.3 (starting from 2.0.0, I believe, up to 2.3.1). All of them result in this same behavior. Therefore it's not in Merlin itself, but probably in my Emacs.

The `messages` buffer does not show any errors. Merlin's history works as expected (even when it jumps to an incorrect place, jumping back returns to the original position).

I wonder if this could be a conflict with another Emacs package? An issue with my Emacs version (24.3.1)? If anyone has seen this happen and has a solution, I'd be really thankful!

**Note**: I tried following the instructions in https://github.com/the-lambda-church/merlin/issues/234 (e.g. adding `FLG -debug locate,/tmp/merlin-locate-debug.txt` to my `.merlin`), and my debug file showed this when trying to go to the definition of function `f`:

    {"time":49,"level":"info","section":"locate","title":null,"content":"looking for the source of 'B.f' (prioritizing .ml files)"}
    {"time":49,"level":"info","section":"locate","title":null,"content":"lookup in value namespace"}
    {"time":49,"level":"info","section":"locate","title":null,"content":"<local buffer>"}

**Comment by trefis** [comment]
I wonder if this could be related to the recent support for `-keep-locs`.
Are you compiling your project with that flag?

**Comment by thranur** [comment]
Wow, that seems to hit the spot!
Apparently this option has been introduced in January in my code base, I had never noticed it before.

**Comment by trefis** [comment]
Ok so, the fixes for `-keeps-locs` actually haven't made it to any release.
Could you opam pin the "beta" branch of this repository and see if it works better for you? (Alternatively, you can just not use `-keep-locs` until we release a new version of merlin)

**Comment by thranur** [comment]
Indeed, the `beta` branch fixes it, thanks!
