### ISSUE TITLE
Bad error message 

### ISSUE THREAD

**Issue by objmagic** [the-lambda-church/merlin#509]
Merlin 2.3.1 gives warning

````
Warning 21: this statement never returns (or has an unsound type.)
````

for code:

````OCaml
let f pred x y = if pred then (print_endiline "123"; x) else y 
````

However, ``ocamlc`` gives error

````
Error: Unbound value print_endiline
Hint: Did you mean print_endline?
````

**Comment by def-lkb** [comment]
Fixed in current master. I leave the issue open, this should be tested for regression when we find a convenient architecture to do that.
