### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by KyleLH** [the-lambda-church/merlin#510]
I clean installed merlin, ocaml, and opam and added the lines suggested to add to my `.vimrc` file, however there were a couple dependencies missing that weren't installed. Namely:

```
jsonm
re
cudf
dose
cmdliner
ocamlgraph
```
any way these could be installed by default?

**Comment by def-lkb** [comment]
But Merlin doesn't rely on any of those. You should install these separately.

**Comment by def-lkb** [comment]
I guess you opened an OCaml file from project that depend on these.
So Merlin said that it would need the dependencies to be satisfied in order to work properly.

**Comment by KyleLH** [comment]
No way, that's awesome! I'll close this then, definitely not a problem with merlin! One question though, do you have any idea why it'd keep saying that I didn't have a module installed, even after I installed it? I was having trouble with `dose`, and even when I ran `opam install dose`, it would complain it couldn't load the package

**Comment by def-lkb** [comment]
The `.merlin` file provided by your project might be wrong.
The findlib package name is `dose3`, not `dose`.
