### ISSUE TITLE
Same module names in different packages causes error

### ISSUE THREAD

**Issue by benedictleejh** [the-lambda-church/merlin#512]
When trying to get Merlin working with [Eliom](http://ocsigen.org/eliom/), I keep getting errors like

```
The files ~/.opam/4.02.3/lib/eliom/server/eliom_pervasives.cmi
~/.opam/4.02.3/lib/eliom/client/eliom_client.cmi
make inconsistent assumptions over interface Eliom_wrap
```

After some searching it seems that Eliom uses the same module names in different packages, which seems to cause Merlin to get confused as to which module in which package is being referenced. Attempting to manually reference the `*.cmi` and `*.cmt` files using `CMI` and `CMT` in the `.merlin` file (as talked about in #70) makes no difference.

My `.merlin` file is as follows:

```
S ./
B _server/
B _client/

PKG lwt
PKG eliom.server eliom.client

PKG eliom.ppx eliom.ppx.client
```

The project (a newly created Eliom project) compiles fine, so I presume there's some issue with how Merlin finds the modules.

Is there any solution to this? Or is it simply not possible to fix it at the moment?

**Comment by Drup** [comment]
> The project (a newly created Eliom project) compiles fine, so I presume there's some issue with how Merlin finds the modules.

I would rather say that eliom is doing non-standard ocaml things. Merlin's behavior is correct.
1. .eliom files will not be handled by merlin, there are no workaround for that for now
2. for other files, I would advise you to use `client/` and `server/` subdirectories and use `PKG eliom.server` inside `server/` (and resp for client). Do not mix `eliom.server` and `eliom.client`.

**Comment by def-lkb** [comment]
Sorry, we cannot do that for now. But in the future it might be possible to provide some support.
