### ISSUE TITLE
merlin protocol documentation issue

### ISSUE THREAD

**Issue by eriklovlie** [the-lambda-church/merlin#515]
Hi, I'm trying to use merlin to make a linter for atom. I've got things mostly working with version 2.3.1, however I'm now wondering how I deal with files that are moved or renamed? I wasn't able to tell (pun intended) from the (very nice btw) protocol documentation how to make merlin forget a file/buffer, or alternatively update its file path.

Can I ask if this is documented somewhere?

**Comment by let-def** [comment]
Sorry, I had no time to answer a month ago and after I forgot... No there is no way to tell merlin a file is moved or renamed.
Just create a new buffer with the same content.

**Comment by let-def** [comment]
(I will remember to add an optional forget command... Or maybe some caching strategy to collect old buffers. And thanks for your work with atom)

**Comment by eriklovlie** [comment]
Thanks for the info :)
