### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by G4143** [the-lambda-church/merlin#519]
Just a heads up. Ubuntu 16.04 has moved from Python 2.7 to Python 3.x and merln/vim doesn't work with the newer Python.

**Comment by def-lkb** [comment]
Thanks for the information, git version should work with both python2 and python3.

**Comment by darioteixeira** [comment]
I've just came across this problem.  With Merlin 2.3.1 and a fresh install of Kubuntu 16.04 I get the message `Error: Required vim compiled with +python`.  However, after `opam pin add merlin --dev-repo`, the message becomes `Error: Required vim compiled with +python or +python3`. Any ideas?

**Comment by def-lkb** [comment]
Update: branch `beta` is Merlin 2.3.1 with various bugfixes and support for python3.

@darioteixeira: can you share the output of `:version`?

**Comment by darioteixeira** [comment]
@def-lkb: Okay, so I switched from Merlin#master to Merlin#beta, but the problem remains.  In fact, the output of `:version` is exactly the same:


````
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             +cmdline_info    +eval            +insert_expand   +modify_fname    -mzscheme        +rightleft       +terminfo        +wildignore
+arabic          +comments        +ex_extra        +job             +mouse           +netbeans_intg   -ruby            +termresponse    +wildmenu
+autocmd         +conceal         +extra_search    +jumplist        -mouseshape      +packages        +scrollbind      +textobjects     +windows
-balloon_eval    +cryptv          +farsi           +keymap          +mouse_dec       +path_extra      +signs           +timers          +writebackup
-browse          +cscope          +file_in_path    +langmap         +mouse_gpm       -perl            +smartindent     +title           -X11
++builtin_terms  +cursorbind      +find_in_path    +libcall         -mouse_jsbterm   +persistent_undo +startuptime     -toolbar         -xfontset
+byte_offset     +cursorshape     +float           +linebreak       +mouse_netterm   +postscript      +statusline      +user_commands   -xim
+channel         +dialog_con      +folding         +lispindent      +mouse_sgr       +printer         -sun_workshop    +vertsplit       -xsmp
+cindent         +diff            -footer          +listcmds        -mouse_sysmouse  +profile         +syntax          +virtualedit     -xterm_clipboard
-clientserver    +digraphs        +fork()          +localmap        +mouse_urxvt     -python          +tag_binary      +visual          -xterm_save
-clipboard       -dnd             +gettext         -lua             +mouse_xterm     -python3         +tag_old_static  +visualextra     -xpm
+cmdline_compl   -ebcdic          -hangul_input    +menu            +multi_byte      +quickfix        -tag_any_white   +viminfo
+cmdline_hist    +emacs_tags      +iconv           +mksession       +multi_lang      +reltime         -tcl             +vreplace
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FO
RTIFY_SOURCE=1
Linking: gcc   -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux -lacl -lattr -lgpm -ldl
````

**Comment by raphael-proust** [comment]
@darioteixeira your vim is compiled without support for python (the two entries in the output of `:version` that say `-python` and `-python3`).

I don't know Debian/Ubuntu very well so I'm not sure how to get a package with python support.

**Comment by G4143** [comment]
I tried removing vim on Ubuntu 16.04 and installing vim-gnome which is compiled for Python3 and I still have problems with the latest Merlin. Here's version's blurb..

> 
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 11:38:28)
Included patches: 1-1689
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgnomeui-2.0 -I/usr/include/gnome-keyring-1 -I/usr/include/libbonoboui-2.0 -I/usr/include/libxml2 -I/usr/include/libgnome-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/orbit-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.0 -I/usr/include/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lgnomecanvas-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgdk_pixbuf-2.0 -lgnomevfs-2 -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm     

> 

And here's what happened when I tried to open my.ml with vim..

> 
Error: Required vim compiled with +python
Error detected while processing /home/gerard/.opam/4.02.1/share/merlin/vim/ftplugin/ocaml.vim:
line    2:
E117: Unknown function: merlin#Register
>

**Comment by darioteixeira** [comment]
@raphael-proust: Yes, the problem likely stems from just a small change in the Vim package between (K)Ubuntu 15.10 and (K)Ubuntu 16.04.  Indeed, running `apt-cache search vim | grep "^vim" | grep py` yields a bunch of interesting packages:
````
vim-athena-py2 - Vi IMproved - enhanced vi editor - with Athena GUI (Python2)
vim-gnome-py2 - Vi IMproved - enhanced vi editor - with GNOME2 GUI (Python2)
vim-gtk-py2 - Vi IMproved - enhanced vi editor - with GTK2 GUI (Python2)
vim-gtk3-py2 - Vi IMproved - enhanced vi editor - with GTK3 GUI (Python2)
vim-nox-py2 - Vi IMproved - enhanced vi editor - with scripting languages support (Python2)
vim-python-jedi - autocompletion tool for Python - VIM addon files
````
After installing `vim-nox-py2`, issuing `:version` inside Vim now tells me that `python` is supported. Also, Merlin seems to be working fine.  Thanks!

**Comment by def-lkb** [comment]
@G4143: this is stable version of Merlin, you need to use the git one.

```shell
opam pin add merlin https://github.com/the-lambda-church/merlin#beta
```

**Comment by G4143** [comment]
I tried darioteixeira's solution "vim-nox-py2" on Ubuntu 16.04 and it work! That's for the help everyone and thank-you merlin maintainers.
