### ISSUE TITLE
4.03+flambda: foo.cmt is not a compiled interface

### ISSUE THREAD

**Issue by bluddy** [the-lambda-church/merlin#523]
I keep getting this error when looking up in other files. The files definitely exist and I cleaned before rebuilding them.

**Comment by let-def** [comment]
Support for 4.03 is still experimental. I plan to release an update next week.

**Comment by let-def** [comment]
Can you try with current master? This should work as expected.

**Comment by bluddy** [comment]
I'm getting installation problems with opam pin. Specifically, none of the share files appear where they should be.

Looking at the opam file, does the 'prefix' variable exist? Also, the rm command is trying to delete a non-existent directory, with the result that I still have my old .pyc files.

**Comment by let-def** [comment]
```shell
$ opam config var prefix
/home/def/.opam/4.03.0
```

You can try on your machine.

**Comment by bluddy** [comment]
So looking at your recent commit, it wasn't my config but a file that got messed up?
I'm trying to pin master now and I get a compilation error.

# Error: The implementation src/ocaml/lexer_raw.ml
# [...]
#            mutable comment_start_loc : Location.t list;
#            mutable preprocessor : preprocessor option;
#          }
#        File "src/ocaml/preprocess/lexer_raw.mll", line 53, characters 0-197:
#          Actual declaration
#        The mutability of field buffer is different.

**Comment by let-def** [comment]
Can you start from a fresh clone?

**Comment by bluddy** [comment]
My bad! I had a change to the opam file that persisted after pulling.

It works! Yay! So happy Merlin's back. Thank you so much for your tireless efforts.

**Comment by let-def** [comment]
You are welcome, situation is a bit shaky during transition to 4.03.
