### ISSUE TITLE
Improvement for type check info about classes.

### ISSUE THREAD

**Issue by fxfactorial** [the-lambda-church/merlin#524]
say we have:

```ocaml
class foo ?arg1 ?arg2 ~last () = object
...blah blah
end
```

Then when using merlin like so 

`let a = new foo` and doing a type check over foo gives us back the structural type of foo, this isn't as useful as knowing the args that foo takes when creating a new object, aka its parameters.

Maybe it can be changed like how named poly variants are handled, aka show me the type first, then if i check type again on same thing do a drill down of the individual variants. So for this, give me the signature of what args the object takes, then if I do it again give me the structural type.

**Comment by let-def** [comment]
@fxfactorial Type enclosing is handling this situation in a satisfying way I think. Either ask type on `new` or press `ctrl-up` after getting the type of `foo`.
What do you think?

**Comment by fxfactorial** [comment]
yes, vote for doing it on new.

**Comment by let-def** [comment]
Maybe we can close this issue then?
