### ISSUE TITLE
ppx_let not being applied

### ISSUE THREAD

**Issue by imeckler** [the-lambda-church/merlin#525]
Hi all,

In a minimal example, I have my `.merlin` as
```
PKG ppx_let
PKG async
```

and the `.ml` file
```ocaml
open Async.Std

let _ =
  let%map () = return () in
  ()
;;
```

The merlin syntax checker shows the error
```
Parse error: "module" or "open" or [opt_rec] expected after "let" (in [expr])
```

Any pointers on if/how merlin can be configured to apply the ppx?

**Comment by let-def** [comment]
This error message is not produced by merlin.
I would guess that you are using syntastic and that syntastic is using `camlp4o` checker.
You can check that with `:SyntasticInfo`.

Then `let g:syntastic_ocaml_checkers = ['merlin']` will fix the problem.

**Comment by imeckler** [comment]
Indeed. Thank you Frédéric!
