### ISSUE TITLE
emacs merlin-locate failing after a comment containing #5

### ISSUE THREAD

**Issue by chambart** [the-lambda-church/merlin#529]
locate fail when running on:
```
let a = List.length
(* PR#5513 *)
let b = List.length
```
It works with the cursor on the definition of `a`, and fail on `b` with `Not a valid identifier`

Note that merlin-locate-ident at the same point called with `List.length` does work.

**Comment by trefis** [comment]
`¯\_(ツ)_/¯`

**Comment by chambart** [comment]
Is there some easy way to log what was sent to merlin ?

**Comment by trefis** [comment]
Yes!
You can log all the exchanges between your editor and merlin by setting the `MERLIN_LOG` environment variable before starting/restarting merlin. If you set it to `/tmp/merlin.log` it will log every exchange there.

Then you can specifically log what locate is doing by setting something like `FLG -debug locate:debug,/tmp/locate.log` in your .merlin.

**Comment by chambart** [comment]
I changed the file for simple logs, and it appears to be coming from merlin:
```
let f x = x
let a = f
(* PR#5513 *)
let b = f
```
The working part:
```
# 0.02 frontend - input
{
  "document": [ "auto", "/tmp/plop.ml" ],
  "query": [ "locate", null, "ml", "at", { "line": 2, "col": 8 } ]
}
# 0.02 track_definition - from_string
looking for the source of 'f' (prioritizing .ml files)
# 0.02 track_definition - lookup
lookup in value namespace
# 0.02 track_definition - find_source
failed to find "Plop" in source path (fallback = false)
# 0.02 track_definition - find_source
(for reference: fname = "plop.ml")
# 0.02 track_definition - find_source
looking in '/tmp'
# 0.02 track_definition - Locate
/tmp/plop.ml
# 0.02 frontend - output
{
  "class": "return",
  "value": { "file": "/tmp/plop.ml", "pos": { "line": 1, "col": 4 } },
  "notifications": []
}
```

The failing part:
```
# 0.02 frontend - input
{
  "document": [ "auto", "/tmp/plop.ml" ],
  "query": [ "locate", null, "ml", "at", { "line": 4, "col": 8 } ]
}
# 0.02 frontend - output
{ "class": "return", "value": "Not a valid identifier", "notifications": [] }
```

I wouldn't be surpised that it is some lexing problem. I can have a look

**Comment by trefis** [comment]
Oh you're using master.

**Comment by chambart** [comment]
Yes, and apparently merlin doesn't know anymore about those debug flags

**Comment by chambart** [comment]
Thanks. Only `-` is my kind of patch too !

**Comment by let-def** [comment]
You are welcome :)
