### ISSUE TITLE
Merlin reports wrong error for “shadowed” identifiers

### ISSUE THREAD

**Issue by smondet** [the-lambda-church/merlin#533]
With Merlin pinned to https://github.com/the-lambda-church/merlin.git#reason-0.0

I get the same error with Reason and OCaml files (and from Atom and Neovim):

In a file:

```
let x = 42;
let x () => 42;
```

I get this error from Merlin:

```
Error: Values do not match:
         let x : unit => int
       is not included in
         let x : int: /Users/sebastienmondet/test2.re:1
```

**Comment by let-def** [comment]
Fixed in master. Need to find a way to sync with Reason.
