### ISSUE TITLE
bigarray indexing gives an error

### ISSUE THREAD

**Issue by nilsbecker** [the-lambda-church/merlin#534]
hi, from this line:

```
        rhommmd.{i,j} <- rhomm.{i,j};
```
i get an `Error: Unbound value .{,}` . this is with vim, using merlin as a syntastic checker, if that's relevant. the .ml file compiles just fine.

**Comment by let-def** [comment]
This is 4.03 feature which is not well supported by merlin 2.3.1. Please use the git master branch for 4.03 support.

**Comment by nilsbecker** [comment]
ah ok, i thought this was old syntax.

**Comment by let-def** [comment]
It was, but there was also an updated proposal for 4.03 which was reverted for official release.
Merlin 2.3.1 far before 4.03, so only featured a "preview" which was branched before the revert.
