### ISSUE TITLE
Merlin could not show type hints in some situation

### ISSUE THREAD

**Issue by liweijian** [the-lambda-church/merlin#535]
I was reading the source code of [facebook's flow](https://github.com/facebook/flow/tree/master/src/parser)

I could figure out the type of the function `run` ([source](https://github.com/facebook/flow/blob/master/src/parser/tools/native_test_files.ml)) as:

![2 pic_hd](https://cloud.githubusercontent.com/assets/19320783/15490612/397aa61e-219c-11e6-8788-435a6445bdab.jpg)

However, when I tried to find the type of `program` inside `run`, there's nothing:
![3 pic](https://cloud.githubusercontent.com/assets/19320783/15490644/81f7fcca-219c-11e6-82c6-c4cbaae3c8de.jpg)

The merlin configure file in the root of project:
```
S hack/**
S src/**

B _build/**
```

**Comment by liweijian** [comment]
![4 pic](https://cloud.githubusercontent.com/assets/19320783/15490939/9605829e-219e-11e6-8edf-cf6ed633c2a5.jpg)

There's signature error on the file [parser_flow.ml](https://github.com/facebook/flow/blob/master/src/parser/parser_flow.ml) as above, but I could `make` this project and found no error as:
```bash
$ make  
cd /Users/liweijian/wizard/flow/src/parser//../..; \
	ocamlbuild -no-links src/parser/parser_flow.cmxa
Finished, 21 targets (8 cached) in 00:00:01.
```

**Comment by let-def** [comment]
Thanks for the detailed report.

In the first case, you can see that `fail:bool ->` started appearing at the bottom of the screen.
The vim invocation magic slightly changed in latest version, it should work the git master.

For the second bug, I couldn't reproduce, it worked as expected.
Which versions of Merlin and OCaml are you using?

**Comment by liweijian** [comment]
```bash
$ ocaml --version
The OCaml toplevel, version 4.03.0

$ ocamlmerlin  -version                        
The Merlin toolkit version 2.3.1, for Ocaml 4.03.0
```
And the vim version is
> MacVim :  Custom Version 7.4 (104)

As you mentioned:
> The vim invocation magic slightly changed in latest version, it should work the git master.

Should I update vim or merlin?

Thanks:)

**Comment by let-def** [comment]
4.03 is not well supported by Merlin 2.3.1.
To use the git version, try `opam pin add merlin https://github.com/the-lambda-church/merlin.git`.
Don't forget to unpin when an official version is released.

You can keep your version of vim (although at some point switching to neovim will make everybody's life easier :P).

**Comment by liweijian** [comment]
I think I'd better switch ocaml back to 4.02.3:(

I tried to install neovim, however when I want to install a GUI for neovim, there's always an error:
```
ld: library not found for -lmsgpack
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [build/Neovim.app/Contents/MacOS/Neovim] Error 1
make: *** [all] Error 2
```

I may switch to neovim when its version 1.0 release.

**Comment by let-def** [comment]
Release should come in ~ two weeks :).
