### ISSUE TITLE
merlin 2.3.1 with OCaml 4.03.0 reports incorrect signature mismatch for optional argument in module type

### ISSUE THREAD

**Issue by lijunsong** [the-lambda-church/merlin#537]
This happens on ocaml 4.03.0, with merlin 2.3.1. Take this simple example.

```ocaml
module type I =
sig
  val h : bool
end

module type S =
sig
  val go: ?p:bool -> unit -> bool
end


module Make (Input : I) : S =
struct
  let go ?(p=true) () =
    if Input.h then true
    else p
end
```

Merlin reports
```
Error: Signature mismatch:
       Values do not match:
         val go : ?p:bool -> unit -> bool
       is not included in
         val go : ?p:bool option -> unit -> bool
```
Be aware the `bool option`.

With OCaml 4.02.3, merlin 2.3.1 works fine.

**Comment by trefis** [comment]
As explained here https://github.com/the-lambda-church/merlin/issues/534 Merlin 2.3.1 doesn't support ocaml 4.03 all that well.

Try opam pining the master branch of the git repository.

**Comment by lijunsong** [comment]
Oops. Thanks.
