### ISSUE TITLE
Will merlin support generate function list and module list tags?

### ISSUE THREAD

**Issue by liweijian** [the-lambda-church/merlin#539]
I tried to use [taglist](https://github.com/vim-scripts/taglist.vim) to generate function list and method list for OCaml project, it's horrible.

I'm using merlin to hint the type of function and jump to the definition of the function, I was wondering if merlin support generate taglist's tags?

**Comment by let-def** [comment]
It does but not in the taglist format. Maybe ctrlp will provide what you want (also read :MerlinOutline and :MerlinILocate documentation)?
