### ISSUE TITLE
Invalid detection of escaping type of the inlined record

### ISSUE THREAD

**Issue by wieczyk** [the-lambda-church/merlin#540]
Minimal testcase:
```
type test = Test of
    { name  : string
    }

let name_of_test (Test n) = n.name
```

Merlin emits error: `This form is not allowed as the type of the inlined record could escape.` while ocaml does not have problem with this code.

**Comment by liweijian** [comment]
As far as I know, 4.03 is not well supported by Merlin 2.3.1. But the new release should come in one week:)

**Comment by liweijian** [comment]
However you can try the git version to fix this issue by `opam pin add merlin https://github.com/the-lambda-church/merlin.git`, but don't forget to unpin when the official new version is released.

**Comment by let-def** [comment]
As @liweijian said, 4.03 support is coming slowly.
This was an actual bug in merlin's port of typechecker, thanks for reporting.
Hopefully it should be stable soon :).

**Comment by wieczyk** [comment]
Nice, thanks.

I was comparing typecore.ml to one from the OCaml 4.03.0 source code but I did not figure out where is a problem ;/
