### ISSUE TITLE
Latest Opam distribution does not include emacs plugin

### ISSUE THREAD

**Issue by hoheinzollern** [the-lambda-church/merlin#541]
Hi all, when I try to install merlin through opam on OSX Yosemite, after doing an update, I find that my local `.opam/system/share/merlin/` folder contains only the vim plugins and not the emacs ones, which previously worked fine.

**Comment by let-def** [comment]
The files should be in `.opam/system/share/emacs`. 
If not, that's a bug.
This behavior was chosen to align with other packages providing emacs modes.

**Comment by hoheinzollern** [comment]
It is indeed. My emacs configuration broke after an update and I did not realise the folder was moved. Simply copy pasting the new quick setup fixed the problem for me. Thanks for the support!
