### ISSUE TITLE
s.[n] (shortcut for String.get s n) unrecognized

### ISSUE THREAD

**Issue by ghilesZ** [the-lambda-church/merlin#542]
Self explanatory.

**Comment by raphael-proust** [comment]
Version number? Other details?

**Comment by ghilesZ** [comment]
with ocaml 4.03.0, and merlin 2.3.1.

Btw a.(n), shortcut for for Array.get a n does not work either

2016-06-09 10:25 GMT+02:00 Raphaël Proust <notifications@github.com>:

**Comment by liweijian** [comment]
OCaml 4.03.0 does not well support at this merlin version.

**Comment by let-def** [comment]
Release for 4.03.0 should happen today or tomorrow.

**Comment by ghilesZ** [comment]
Thanks it works !

2016-06-14 8:39 GMT+02:00 Frédéric Bour <notifications@github.com>:
