### ISSUE TITLE
Merlin provide a hook for other languages. 

### ISSUE THREAD

**Issue by fxfactorial** [the-lambda-church/merlin#543]
Bear with me. Imagine we had this: 

```ocaml
let () = 
  let foo = 123 in
  let bar = 456 in
  let from_js = [js_code% 
   (function () { return true;})()] 
  in
  print_bool from_js
```

And what I was thinking is for merlin to see this `js_code` extension and itself call another another program (configurable of my choosing in this case `ternjs`), to get the type check info and give it back to me when I do `C-c C-t`, aka merlin check the type.

**Comment by let-def** [comment]
This is vague and I am afraid we don't have the resources to implement such feature in the short term.

I will close it for now, but feel free to come back and post more information in the future.

**Comment by fxfactorial** [comment]
Thanks
