### ISSUE TITLE
merlin 2.3.1 does not build with ocaml 4.02.0

### ISSUE THREAD

**Issue by ysalmon** [the-lambda-church/merlin#545]
I tried to install the merlin package on my 4.02.0 opam switch, but this fails with the following
```
#=== ERROR while installing merlin.2.3.1 ======================================#
# opam-version 1.2.2
# os           linux
# command      make -j 4
# path         /home/yann/.opam/4.02.0/build/merlin.2.3.1
# compiler     4.02.0
# exit-code    2
# env-file     /home/yann/.opam/4.02.0/build/merlin.2.3.1/merlin-32510-4d7566.env
# stdout-file  /home/yann/.opam/4.02.0/build/merlin.2.3.1/merlin-32510-4d7566.out
# stderr-file  /home/yann/.opam/4.02.0/build/merlin.2.3.1/merlin-32510-4d7566.err
### stdout ###
# make -f Makefile.ocamlmakefile WITH_BIN_ANNOT="" WITH_DEBUG="" REALLY_QUIET=1 ocamlmerlin
# make[1] : on entre dans le répertoire « /home/yann/.opam/4.02.0/build/merlin.2.3.1 »
# make[2] : on entre dans le répertoire « /home/yann/.opam/4.02.0/build/merlin.2.3.1 »
# OCamlMakefile:1076 : la recette pour la cible « src/ocaml/typing/typecore.cmx » a échouée
# make[2] : on quitte le répertoire « /home/yann/.opam/4.02.0/build/merlin.2.3.1 »
# OCamlMakefile:777 : la recette pour la cible « native-code » a échouée
# make[1] : on quitte le répertoire « /home/yann/.opam/4.02.0/build/merlin.2.3.1 »
# Makefile:57 : la recette pour la cible « ocamlmerlin » a échouée
### stderr ###
# File "src/ocaml/typing/typecore.ml", line 3075, characters 10-19:
# Error: This function has type
#          string -> Parsetree.expression list -> Parsetree.expression
#        It is applied to too many arguments; maybe you forgot a `;'.
# make[2]: *** [src/ocaml/typing/typecore.cmx] Erreur 2
# make[2]: *** Attente des tâches non terminées....
# make[1]: *** [native-code] Erreur 2
# make: *** [ocamlmerlin] Erreur 2
```

I did not manually change the compiler source in my opam installation. What is going on ?

**Comment by let-def** [comment]
Merlin doesn't support 4.02.0. Do you have any reason not to use 4.02.{1,2,3}?

**Comment by ysalmon** [comment]
Yes, there does not seem to be an opam switch for 4.02.{1,2,3} with the [patch by Arthur Charguéraud](https://github.com/charguer/ocaml) to get improved error messages, like 4.02.0+improved-errors.
I am currently looking for a good setup for my students next years ; improved-errors is a must and merlin might be interesting too.

**Comment by dbuenzli** [comment]
@ysalmon IIRC 4.02.0 had horrendous compilation times so it was not widely used by anyone. Maybe the  patch can be ported to 4.02.1 as is ?

**Comment by dbuenzli** [comment]
I'm sure the folks maintaining the OPAM repo will create a switch for this if that is the case.

**Comment by let-def** [comment]
I can provide a patch for 4.02, but I would prefer @dbuenzli suggestion. It is not good to use 4.02.0 in general.

**Comment by ysalmon** [comment]
Thanks for this information ; I was not aware of this performance problem in 4.02.0 as we do not compile big programs. I will get in touch with Arthur Charguéraud to see if he can provide a patch for a better version of the compiler.

**Comment by let-def** [comment]
Be careful when setting up development environment: Merlin will display normal type error messages.
You may want to use Merlin only for type information and completion, and the normal edit-compile-fix cycle to get error messages.

**Comment by ysalmon** [comment]
Thanks for your help. You are right, it does not make sense to support 4.02.0 if it is flawed.
So we'll be using merlin in the future, but not just yet (mind you, we're still officially supposed to use Caml Light, so we are coming a long way !).
