### ISSUE TITLE
Tweak OCAMLPATH per project (feature)

### ISSUE THREAD

**Issue by gerdstolpmann** [the-lambda-church/merlin#546]
Hi,

I often want to use libraries before they are installed (permitting a quicker edit/compile cycle). When building my projects I simply set OCAMLPATH, e.g. ```OCAMLPATH=../../dir/src make```. This works well so far the imported libraries have the right directory layout that ocamlfind expects. I wonder whether merlin could also support this, e.g. via a PATH setting in `.merlin`:
```
PATH ../../dir/src
```
in the root `.merlin`file would prepend this path to OCAMLPATH.

Gerd

**Comment by trefis** [comment]
Isn't that equivalent to merlin's [build path](https://github.com/the-lambda-church/merlin/wiki/project-configuration#build-path)?

**Comment by let-def** [comment]
@trefis: I understand that @gerdstolpmann want to use merlin with a different standard library.

`STDLIB ../../dir/src` in .merlin should do exactly that, but I must say I didn't use that setup much.
Is it what you expected?

**Comment by let-def** [comment]
@gerdstolpmann ping?

**Comment by gerdstolpmann** [comment]
Sorry, did not get notification emails.

It's not about changing the stdlib path. It's about a workflow where you edit several projects that depend on each other, and that will finally be installed as separate libraries. E.g. project1 needs project2. Compiling that is easy, just set OCAMLPATH before you build project1 so that the not-yet-installed project2 is found.

**Comment by gerdstolpmann** [comment]
added PR https://github.com/the-lambda-church/merlin/pull/552
