### ISSUE TITLE
Suggested Emacs configuration has a number of issues

### ISSUE THREAD

**Issue by cpitclaudel** [the-lambda-church/merlin#547]
Hi,

I'm currently setting up merlin; it looks very cool. 

There are a number of problems with the suggested Emacs configuration though.  I've listed them below, in the hope that they may be useful :) For reference, here's what `opam install merlin` suggests:

```
   Add opam emacs directory to your load-path by appending this to your .emacs:
     ;; Add opam emacs directory to the load-path
     (setq opam-share (substring (shell-command-to-string "opam config var share 2> /dev/null") 0 -1))
     (add-to-list 'load-path (concat opam-share "/emacs/site-lisp"))
     ;; Load merlin-mode
     (require 'merlin)
     ;; Start merlin on ocaml files
     (add-hook 'tuareg-mode-hook 'merlin-mode t)
     (add-hook 'caml-mode-hook 'merlin-mode t)
     ;; Enable auto-complete
     (setq merlin-use-auto-complete-mode 'easy)
     ;; Use opam switch to lookup ocamlmerlin binary
     (setq merlin-command 'opam)
```

Here are the issues:

* The `opam-share` variable isn't defined prior to assignment: it should most likely be a `defvar`, or better a local binding.
* Error handling in this piece of code seems broken; if `opam config var share` produces an error it is swallowed, and then `concat` produces `"/emacs/site-lisp"` as the full path, which causes `require` to fail. Alternatively, if opam isn't found, `substring` throws an `out-of-range` error.
* `concat` is not ideal with paths; `expand-file-name` is generally better
* `require` loads the package instead of registering it for deferred loading. Because of this, Emacs will load merlin on every start, slowing startup down unnecessarily. The proper way to handle this is to ship packages with autoload files (That's what  `;;;###autoload` magic comments are for; there's one in `merlin.el` currently, but it does nothing currently AFAICT).
* Does `merlin-use-auto-complete-mode` do anything?

All in all, the following would probably work:

```elisp
(let ((opam-share (ignore-errors (car (process-lines "opam" "config" "var" "share")))))
  (when (and opam-share (file-directory-p opam-share))
    ;; Register Merlin
    (add-to-list 'load-path (expand-file-name "emacs/site-lisp" opam-share))
    (autoload 'merlin-mode "merlin" nil t nil)
    ;; Automatically start it in OCaml buffers
    (add-hook 'tuareg-mode-hook 'merlin-mode t)
    (add-hook 'caml-mode-hook 'merlin-mode t)
    ;; Use opam switch to lookup ocamlmerlin binary
    (setq merlin-command 'opam)))
```

The main benefits are better error checking and loading merlin lazily.

**Comment by let-def** [comment]
Thanks for your suggestion. I updated the opam message and tried to cleanup autoload cookies.

**Comment by cpitclaudel** [comment]
Thanks. https://github.com/the-lambda-church/merlin/wiki/emacs-from-scratch is still wrong, though.
