### ISSUE TITLE
ocamlmerlin doe not work with ocpwin

### ISSUE THREAD

**Issue by unuunc** [the-lambda-church/merlin#551]
simply execute ocamlmerlin.exe

Fatal error: exception Failure("Config file not found - neither C:\\ocamlmgw\\et
c\\findlib.conf nor the directory C:\\ocamlmgw\\etc\\findlib.conf.d")

I understand that it is expecting findlib conf , is tehre any plan to make it work with ocpwin install
(http://www.ocamlpro.com/pub/ocpwin/ocpwin-builds/ocpwin64/)

**Comment by let-def** [comment]
Exporting `OCAMLFIND_CONF=somepath` should fix your problem.
If you don't have an ocamlfind install, you can provide an empty file or maybe even `NUL` (`/dev/null` works under unix, I am unsure about windows semantics).

**Comment by unuunc** [comment]
providing empty conf file solved the issue. but seems ocpwin is not the best option , I need to install other tools also ocp-indent , opam etc.

Thanks for response.

**Comment by unuunc** [comment]
closing it as original issue resolved
