### ISSUE TITLE
ppx_let not being recognized by merlin?

### ISSUE THREAD

**Issue by KitFreddura** [the-lambda-church/merlin#555]
Hey all,
I've install merlin by building from the git and everything is working well except that it doesn't recognize ppx_let expressions.
My example code is: 
``` 
open Core.Std
open Option.Let_syntax
let opt_add a b = 
let%bind x = a 
and y = b
in Some (x + y)
```
Which runs fine, but merlin thinks that let%bind is a syntax error? I use syntastic and have already set it to use merlin for ocaml files. And I'm using OCaml 4.03, do you have any suggestions? Thanks!

**Comment by copy** [comment]
It should work if you add `PKG ppx_let` to your .merlin.

**Comment by let-def** [comment]
Like @copy said. Thanks :).
