### ISSUE TITLE
Inconsistent type hints

### ISSUE THREAD

**Issue by hackwaly** [the-lambda-church/merlin#559]
It's [reported](https://github.com/hackwaly/vscode-ocaml/issues/37) by @vogler.
>
```ocaml
type t = A | B | C
(* ... *)
let f = function
  | A -> 1
  | _ (* I want to know what can be matched here *) -> 2
```
Currently, when hovering over _ it shows type _ = t and then, when moving the mouse to the start or end of the pattern (is that really what triggers it?), it shows type t = A | B | C.

Here's session logged:
```
command to merlin: ["checkout","auto","Untitled-1"]
response from merlin: ["return",true]
command to merlin: ["tell","start","end","type t = A | B | C\n(* ... *)\nlet f = function\n  | A -> 1\n  | _ (* I want to know what can be matched here *) -> 2"]
response from merlin: ["return",true]
command to merlin: ["type","enclosing","at",{"line":4,"col":4}]
response from merlin: ["return",[{"start":{"line":4,"col":4},"end":{"line":4,"col":5},"type":"type t = A | B | C","tail":"no"},{"start":{"line":3,"col":8},"end":{"line":5,"col":56},"type":"t -> int","tail":"no"}]]

command to merlin: ["checkout","auto","Untitled-1"]
response from merlin: ["return",true]
command to merlin: ["tell","start","end","type t = A | B | C\n(* ... *)\nlet f = function\n  | A -> 1\n  | _ (* I want to know what can be matched here *) -> 2"]
response from merlin: ["return",true]
command to merlin: ["type","enclosing","at",{"line":4,"col":5}]
response from merlin: ["return",[{"start":{"line":4,"col":4},"end":{"line":4,"col":5},"type":"t","tail":"no"},{"start":{"line":3,"col":8},"end":{"line":5,"col":56},"type":"t -> int","tail":"no"}]]
```

Confirmed on `The Merlin toolkit version 2.5.0, for Ocaml 4.03.0`

**Comment by let-def** [comment]
It is a feature of merlin dubbed "verbosity" which makes more sense in the sequential interfaces from Emacs & Vim.

When issuing the same query multiple times, merlin would add more information:
- expand the aliases
- if the definition is a type constructor, reminds the definition of this constructor (here `type t = A | B | C`).

So the log you give seems correct wrt to this behavior: the pattern has type t, and you be reminded of the definition of t (and the hints are consistent).

I understand that it would be better to make it possible to specify the verbosity at the protocol level; this will come in the next version. Would this solve your problem?

**Comment by hackwaly** [comment]
Sure. Thanks for your explanation!
