### ISSUE TITLE
Understanding the context of the cursor point

### ISSUE THREAD

**Issue by roshanjames** [the-lambda-church/merlin#56]
One day merlin should understand the context of the point better. More specifically it should know if:

   1) One is editing a type or an expression.  

   2) The local scope of the expression. Offer locally bound variables
   in the expression.

   3) It would also be great it the type at the current point guided
   what expansion results were offered. I'd imagine that one would
   want both -- one sort of expansion that took the type of the point
   into account and one that did not.

**Comment by let-def** [comment]
Implemented some time ago.
