### ISSUE TITLE
Merlin Occurrences (and Rename) inconsistencies

### ISSUE THREAD

**Issue by eugoss** [the-lambda-church/merlin#564]
If I open the following simple test file in Vim, position the cursor at _foo_ in `let foo s`, run :MerlinOccurrences, the location list shows only this first occurrence, where `foo` is defined.
If I jump to `foo "zzz"`, and invoke :MerlinOccurrences from there, it shows both occurrences of `foo`. If I jump, thereafter, back to the first occurrence, it shows both two as well.

It's interesting that it works just fine, for example, for `host` defined in `foo`. It always shows both the definition and usage occurrences regardless of the first cursor position.

```ocaml
let foo s =
  let host = "bar" in
  print_endline host;
  print_endline s

let () =
  foo "zzz"
```

**NOTE** :MerlinRename is broken similarly. It renames both occurrences of *foo* only when the cursor is at the seventh line.

---
OCaml 4.03.0 / Merlin 2.5.0 (from OPAM) / Vim 7.4 (+python -python3)

**Comment by eugoss** [comment]
Now I don't think it's an issue with the Vim plugin.

I replayed the JSON commands sent by Vim to ocamlmerlin.

### The cursor is at the first line

*cmd1.json:*
```json
{"query": ["project", "get"], "context": ["auto", "/home/eugene/work/test.ml"]}
{"query": ["tell", "start", "end", "let foo s =\n  let host = \"bar\" in\n  print_endline host;\n  print_endline s\n\nlet () =\n  foo \"zzz\"\n"], "context": ["auto", "/home/eugene/work/test.ml"]}
{"query": ["occurrences", "ident", "at", {"line": 1, "col": 4}], "context": ["auto", "/home/eugene/work/test.ml"]}
```

```bash
$ ocamlmerlin < cmd1.json
```
```json
["return",{"result":[]}]
["return",true]
["return",[{"start":{"line":1,"col":4},"end":{"line":1,"col":7}}]]
```

### The cursor is at the seventh line

*cmd2.json:*
```json
{"query": ["project", "get"], "context": ["auto", "/home/eugene/work/test.ml"]}
{"query": ["tell", "start", "end", "let foo s =\n  let host = \"bar\" in\n  print_endline host;\n  print_endline s\n\nlet () =\n  foo \"zzz\"\n"], "context": ["auto", "/home/eugene/work/test.ml"]}
{"query": ["occurrences", "ident", "at", {"line": 7, "col": 2}], "context": ["auto", "/home/eugene/work/test.ml"]}
```

```bash
$ ocamlmerlin < cmd2.json
```
```json
["return",{"result":[]}]
["return",true]
["return",[{"start":{"line":1,"col":4},"end":{"line":1,"col":7}},{"start":{"line":7,"col":2},"end":{"line":7,"col":5}}]]
```

**Comment by Khady** [comment]
I experienced the same kind of issue. The first time I use occurrences I
don't have the full list of expected occurrences. But if I try again after
a locate on one of the occurrences the list seems complete. I haven't tried
to call occurrences twice in a row.

On emacs, with merlin 2.5 from opam.

2016-09-05 14:35 GMT+08:00 Eugene Ossintsev <notifications@github.com>:
