### ISSUE TITLE
`PKG ppx_deriving` in .merlin will cause [@@deriving show] display error

### ISSUE THREAD

**Issue by qdwang** [the-lambda-church/merlin#566]
`show` in ` [@@deriving show]` will display error as `Cannot locate deriver show`.
Without `PKG ppx_deriving` in .merlin, the above error will not be displayed. 
But `print_endline (show xxx)` will display error as

 `This expression has type Ppx_deriving_runtime.string, but an expression was expected of type string`

**Comment by let-def** [comment]
Cannot reproduce this issue. Which version of merlin, ocaml, etc, are you using?

**Comment by qdwang** [comment]
```
$ ocamlmerlin -version 
The Merlin toolkit version 2.5.0, for Ocaml 4.03.0
```

**Comment by let-def** [comment]
I guess this is an opam managed switch. I still cannot explain the error.
Can you try to reproduce with a git version of merlin?

`opam pin add merlin https://github.com/the-lambda-church/merlin`

**Comment by qdwang** [comment]
I'm now working with the package `ppx_deriving_yojson` and the error never shows.

**Comment by tekknolagi** [comment]
@qdwang I had the same issue, so I changed the line to `PKG ppx_deriving.show` and the issue went away.

**Comment by theindigamer** [comment]
I'm having the same issue using any of: `PKG ppx_deriving.std` or `PKG ppx_deriving` or `PKG ppx_deriving.show`.

Pinned repositories:
```
merlin.3.0.2        git  https://github.com/the-lambda-church/merlin.git
ppx_deriving.4.1    git  https://github.com/whitequark/ppx_deriving.git
```

Output for version:
```
The Merlin toolkit version git-fd21902f855b5bc325625534109612d1b7f7642f, for Ocaml 4.03.0
```
