### ISSUE TITLE
Go-to-definition on Mac OS & Emacs

### ISSUE THREAD

**Issue by correnson** [the-lambda-church/merlin#567]
Going to definition opens a buffer with wrong capitalized name on mac os x.

Typically, when looking for module `A`, Merlin on emacs opens `A.ml` buffer from file `a.ml`, and modifications now go to file `A.ml` and overwrites `a.ml`...

**Comment by dbuenzli** [comment]
Must be related to #425

**Comment by correnson** [comment]
Ok, sorry for duplicate !
