### ISSUE TITLE
Lift the restriction that external identifiers must be functions

### ISSUE THREAD

**Issue by chenglou** [the-lambda-church/merlin#568]
cc @bobzhang

In BuckleScript the FFI might be like this:

```
external foo: document = "document" [@@bs.val]
```

Merlin warns on the first `document` that identifier must be a function. Is it possible to relax this requirement?

**Comment by bobzhang** [comment]
the patch we applied:
https://github.com/bloomberg/ocaml/commit/20146dad4d72751b93806d9d7787f186ebd7d019#diff-aa5ff89b777ddc4932a276703533682aL1327
basically if the external is annotated with `bs`, we loose such restriction

**Comment by let-def** [comment]
This seems minor, we relaxed the check in latest version.

**Comment by joprice** [comment]
I still get this error in vim on a 4.06.1 switch, with merlin 3.3.1. Is the fix in a newer version?

**Comment by trefis** [comment]
No, it had just never been ported to 4.06, 4.07 or 4.08 as they came out.
I pushed a fix in b094c937c3a360eb61054f7652081b88e4f3612f.
