### ISSUE TITLE
[Nuclide-OCaml] How to set the priority of auto-complete?

### ISSUE THREAD

**Issue by liweijian** [the-lambda-church/merlin#569]
I just post it to [nuclide](https://github.com/facebook/nuclide/issues/686), but found it not the right place, so I copy my issue here:)

### Issue and Steps to Reproduce
Auto-complete can save our time in most of the cases, but in some cases it doesn't.

### Expected Behavior
For example, `in` is very common in OCaml, when I typed `in` in Atom and press `enter`. It should only show `in`.

### Actual Behavior
<img width="508" alt="screen shot 2016-09-01 at 3 19 41 pm" src="https://cloud.githubusercontent.com/assets/19320783/18158827/4623aa22-7058-11e6-963a-a26d8fbc70bc.png">

It always shows `in_channel_length`.

### Versions
* Atom:1.9.8
* Nuclide:0.165.0
* Client OS:Mac OS X 10.11.6
* Server OS (optional):

### Additional Details

```shell
├── language-ocaml@1.1.2
├── nuclide@0.165.0
└── ocaml-indent@0.4.0

└── (empty)
```

**Comment by Khady** [comment]
I am not a specialist of atom or any other editor, but I think this is the job of Auto-complete. At least, in my experience with emacs, the plugin I used to auto complete was handling itself a kind of history to show first the most used completion. It basically learn when you use it.

http://auto-complete.org/doc/manual.html#candidate-suggestion

> auto-complete-mode analyzes completion operations one by one and reduces overheads of completion as much as possible. For example, having a candidate "foobar" been completed few times, auto-complete-mode arranges it to top of the candidates next time and make a situation that allows users to complete the word with one time TAB or few times TAB. It is called comphist internally, and you can use it by setting ac-use-comphist to t. It is enabled by default. Collection operations data will be stored in user-emacs-directory or ~/.emacs.d/ with a name ac-comphist.dat.

**Comment by let-def** [comment]
Yes, this issue is not directly related to Merlin.
`in` is a keyword in OCaml but Merlin is focused on semantics so it is not in its scope.

This has to be done somewhere in the editor, but I don't know who is maintaining OCaml & merlin modes for Atom.
