### ISSUE TITLE
Flags ignored by ocamlmerlin are said to be unknown when used in .merlin

### ISSUE THREAD

**Issue by eponier** [the-lambda-church/merlin#574]
On [merlin's main page](https://github.com/the-lambda-church/merlin), it is written that `FLG` in .merlin files accepts the same arguments as ocamlmerlin. However, when using "-c" or "-bin-annot" flags, that are accepted but ignored by ocamlmerlin, I have a notification each time I open an OCaml file in vim:

```
(merlin) project flags: unknown flag: -c
(merlin) project flags: unknown flag: -bin-annot
Unknown flags "-bin-annot", "-c"
```

I don't know if it is a problem of merlin, or of the way vim treats the messages given by merlin (or if it is on purpose ?). What looks strange is that the message is the same for ignored argument of ocamlmerlin and for any other meaningless string.

PS : note that in `ocamlfind --help`, ignored parameters are described as <code>Ignored (ocaml <b>compatility</b>)</code>.

**Comment by let-def** [comment]
Yes this is a mistake. Next major version should fix that.
In the meantime, avoid putting such flags in a `.merlin`.

**Comment by eponier** [comment]
Thank you.

And I now realize that my last line was erroneous and incomprehensible. What I wanted to write is that there is a typo in the help returned by ocamlmerlin.  It reads "compatility" instead of "compatibility".
