### ISSUE TITLE
still can't install merlin on cygwin with opam

### ISSUE THREAD

**Issue by pela9** [the-lambda-church/merlin#581]
Latest version of merlin that I can install on cygwin32 with opam is 2.3.
Version 2.3.1 and also the latest 2.5.0 gives the error.:

#=== ERROR while installing merlin.2.5.0 ======================================#
Some files in ~/.opam/4.02.3/install/merlin.install couldn't be installed:
  - /home/pela/.opam/4.02.3/build/merlin.2.5.0/ocamlmerlin to /home/pela/.opam/4.02.3/bin

My colleagues using the same platform
have the same problem so I don't think I have accidently messed up.
I'm really looking forward to the new features in merlin 2.5 :)

Platform info:
I'm using ocaml 4.02.3 installed with opam on a cygwin32 system
$ uname -rsv
CYGWIN_NT-10.0-WOW 2.6.0(0.304/5/3) 2016-08-31 14:27

**Comment by let-def** [comment]
Could you share install log? Opam produce a few log files and display the path when an install fails.

**Comment by pela9** [comment]
Hello, thanks for the attention. Sorry, but I get no path to a logfile from opam when the installation fails. I've skimmed the logfiles in the .opam/log directory but see only messages concerning previous opam commands.

I have however used the flag -b in the command 'opam upgrade -b' to keep the build directory for merlin 2.5.0. (.opam/4.02.3/build/merlin.2.5.0) after the failed install. No 'ocamlmerlin.exe' has been built, but there is a built executable 'ocamlmerlin_402.exe', can there be a name-error in the install script?

Please let me know if there is more I can do to debug this problem.

**Comment by let-def** [comment]
Yes, that seem very likely.
When working under windows, I recommend using `https://fdopen.github.io/opam-repository-mingw`. It contains fixes for building packages, including the problem you had.

**Comment by pela9** [comment]
By comparing the changes in the merlin build scripts from 2.3 and 2.5.0 I think I have tracked the problem to the if-else branch starting at line 223 in the configure script:

    if [ -z ${COMSPEC+x} ]; then
         ....

COMSPEC is set on a cygwin system causing the test to be false. But this seems to lead to the wrong configuration to be generated. Indeed if I force this test to be true the expected binary is built. I guess the test shall be based on (the later defined) OS_TYPE instead.

**Comment by let-def** [comment]
Latest master includes an updated configure script. I plan to release it soon.

**Comment by let-def** [comment]
Not the end of the story. I have fixes coming tomorrow, finding a testing environment was harder than expected. Sorry.

**Comment by let-def** [comment]
Fixed under latest version. You can try with: `opam pin add merlin --dev-repo`.
