### ISSUE TITLE
Invalid arguments passed by vim to merlin

### ISSUE THREAD

**Issue by bbc2** [the-lambda-church/merlin#583]
Vim and Merlin fail to talk to each other. For instance, `:MerlinTypeOf` triggers an error in vim:

```
Error detected while processing function merlin#TypeOf:
line    4:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bertrand/.opam/4.02.3+PIC/share/merlin/vim/autoload/merlin.py", line 610, in vim_type_enclosing
    enclosing_types = query("type", "enclosing", "at", pos)
  File "/home/bertrand/.opam/4.02.3+PIC/share/merlin/vim/autoload/merlin.py", line 211, in query
    return command(*cmd)
  File "/home/bertrand/.opam/4.02.3+PIC/share/merlin/vim/autoload/merlin.py", line 201, in command
    return merlin_process().command(context(cmd))
  File "/home/bertrand/.opam/4.02.3+PIC/share/merlin/vim/autoload/merlin.py", line 159, in command
    for notification in result['notifications']:
TypeError: list indices must be integers or slices, not str
line    5:
E121: Undefined variable: l:type
E116: Invalid arguments for function <SNR>64_ShowTypeEnclosing
```

In the mentioned Python file, the `result` variable at line 157 contains `['failure', 'invalid arguments']`, which seems to cause the error shown above.

My vim is compiled with Python 3:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 05 2016 03:34:23)
[...]
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
[...]
```
Merlin:
```
The Merlin toolkit version 2.5.0, for Ocaml 4.02.3
```

**Comment by let-def** [comment]
Hmmm... Is the merlin binary coming from `/home/bertrand/.opam/4.02.3+PIC/bin/ocamlmerlin`?
There is some mismatch between vim and merlin, but that's hard to tell where it comes from.

Also, try running vim with `MERLIN_LOG` environment variable set to some log file path and share the file after reproducing the problem: `MERLIN_LOG=merlin_mismatch.log vim test.ml ...`.

**Comment by bbc2** [comment]
Good call.  The ocamlmerlin used by vim came from the `4.02.1+PIC` switch which had merlin 2.3.1.  I forgot to `eval (opam config env)` again in that terminal.  Thank you!
