### ISSUE TITLE
Issue with defvar-local

### ISSUE THREAD

**Issue by bruce-ricard** [the-lambda-church/merlin#584]
My previous installation of Merlin worked perfectly, but this time I was trying to install it (with opam) on my OS X El Capitan Version 10.11.6 with GNU Emacs 22.1.1 and when opening emacs I got an error message from merlin.el and merlin-cap.el that defvar-local is not defined. I changed all those functions to defvar, and I don't have any error message anymore.

**Comment by let-def** [comment]
Yes, we don't try to be compatible with older version of Emacs. Other features might fail.

Try adding this to merlin.el:

```elisp
(unless (fboundp 'defvar-local)
  (defmacro defvar-local (var val &optional docstring)
    `(progn (defvar ,var ,val ,docstring)
            (make-variable-buffer-local (quote ,var)))))
```

If it fixes your problem, I might include this has a compatibility stub in later versions.
