### ISSUE TITLE
Question : Error when starting vim

### ISSUE THREAD

**Issue by JoanThibault** [the-lambda-church/merlin#593]
Hello,

I'm starting with merlin, 5 minutes ago it was working, and now every time I open an .ml file, it raises this error:

"modA.ml" 1L, 11C
Error detected while processing function merlin#Register[117]..merlin#LoadProject:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/joant/.opam/system/share/merlin/vim/autoload/merlin.py", line 740, in setup_merlin
    failures = command("project","get")
  File "/home/joant/.opam/system/share/merlin/vim/autoload/merlin.py", line 201, in command
    return merlin_process().command(context(cmd))
  File "/home/joant/.opam/system/share/merlin/vim/autoload/merlin.py", line 175, in merlin_process
    instance = vim.eval("merlin#SelectBinary()")
vim.error: Vim(echoerr):ocamlmerlin not found!
E171: Missing :endif
Error detected while processing function <SNR>11_LoadFTPlugin:
line   17:
E170: Missing :endfor
Press ENTER or type command 

the file modA.ml only contain one line:
let x = 42

the only thing I did during this 5 minutes was to open a .cpp file

Thank you

**Comment by let-def** [comment]
` vim.error: Vim(echoerr):ocamlmerlin not found!`
Seems you are running this vim from a different shell which doesn't have the right opam setup :).

Try evaluating ``eval `opam config env` ``

**Comment by JoanThibault** [comment]
OK, it works I closed my 15 terminals, to not have this error again =)
Thank you for answering this quickly

I have an other question:
I have two files in my current directory :

-- modA.ml --
let x = 42
-- modB.ml --
let x = ModA.x

when I'm inside modB, merlin raises this error:
  1 modB.ml|1 col 9 error| Unbound module ModA                                  

Any clue?

**Comment by let-def** [comment]
Yes, Merlin works with cmi files produced by the compiler.
You need to integrate your build system (`make`?) with your editor to get a flexible workflow.

Read [vim-from-scratch#configuring-your-project](https://github.com/the-lambda-church/merlin/wiki/vim-from-scratch#configuring-your-project) (the whole page is worth reading too).

**Comment by JoanThibault** [comment]
Ok, thank you
I think you should specify in the doc that we have to do it as soon as we have more than 1 file.
I found the answer to "how to specify ocamlbuild I want to add annotation?"
http://stackoverflow.com/questions/31116013/how-to-tell-oasis-or-ocamlbuild-to-generate-annotations

Thank you again
