### ISSUE TITLE
Syntax error during compilation

### ISSUE THREAD

**Issue by hongchangwu** [the-lambda-church/merlin#595]
`ocaml` version is 4.03.1, OS is Red Hat Enterprise 5.8 (Tikanga). I got the following syntax error when trying to build merlin:

```
File "src/frontend/IO_sexp.ml", line 223, characters 22-31:
Error: Syntax error
OCamlMakefile:1079: recipe for target 'src/frontend/IO_sexp.cmx' failed
```

**Comment by let-def** [comment]
I am surprised, this file has been around for a while and didn't change recently.
Also, I am not aware of a OCaml 4.03.1 release.

Could you give a bit more information (version of merlin, opam too if you are using it)?

**Comment by hongchangwu** [comment]
I was using the LexiFi compiler. I tried OCaml 4.03 and it works fine.
