### ISSUE TITLE
Unable to Locate any source in the core module

### ISSUE THREAD

**Issue by petroav** [the-lambda-church/merlin#597]
The code I am working on is the one shown below. I am trying to Locate `In_channel.fold_lines`.

```
open Core.Std

let build_counts () =
  In_channel.fold_lines stdin ~init:[] ~f:(fun counts line ->
    let count =
      match List.Assoc.find counts line with
      | None -> 0
      | Some x -> x
    in
    List.Assoc.add counts line (count + 1)
  )
```

I have added these two lines to my `.bashrc` and re-installed both merlin and core after adding them:
```
export OPAMKEEPBUILDDIR=true
export OCAMLPARAM="_,bin-annot=1"
```

My Merlin version is 2.1.2 and I am using OCaml 4.02.3. The `.merlin` I have is this:
```
PKG core
CMT /home/someone/.opam/4.02.3/build/core_kernel.113.33.03/_build
FLG -debug locate:debug,/tmp/some_file
```

The contents of `/tmp/some_file` are:

```
{"time":256,"level":"info","section":"locate","title":null,"content":"looking for the source of 'In_channel.fold_lines' (prioritizing .ml files)"}
{"time":256,"level":"info","section":"locate","title":null,"content":"lookup in value namespace"}
{"time":256,"level":"debug","section":"locate","title":null,"content":"present in the environment, but ghost lock. walking up the typedtree."}
{"time":256,"level":"info","section":"locate","title":null,"content":"Core.Std.In_channel.fold_lines not in current file..."}
{"time":256,"level":"debug","section":"locate","title":null,"content":"from_path 'Core'"}
{"time":304,"level":"info","section":"locate","title":null,"content":"inspecting /home/someone/.opam/4.02.3/lib/core/core.cmt"}
{"time":304,"level":"debug","section":"locate","title":null,"content":"File_switching.move_to /home/someone/.opam/4.02.3/lib/core/core.cmt"}
{"time":304,"level":"debug","section":"locate","title":null,"content":"File_switching.allow_movement"}
{"time":304,"level":"debug","section":"locate","title":"loadpath","content":"Saw packed module => erasing loadpath"}
{"time":304,"level":"debug","section":"locate","title":"loadpath","content":"/home/someone/.opam/4.02.3/lib/core"}
{"time":304,"level":"debug","section":"locate","title":"loadpath","content":"src"}
{"time":304,"level":"debug","section":"locate","title":"loadpath","content":"/home/someone/.opam/4.02.3/lib/ocaml"}
{"time":304,"level":"debug","section":"locate","title":"loadpath","content":"Restored load path"}
{"time":304,"level":"info","section":"locate","title":null,"content":"inspecting /home/someone/.opam/4.02.3/build/core_kernel.113.33.03/_build/src/std.cmt"}
{"time":304,"level":"debug","section":"locate","title":null,"content":"File_switching.move_to /home/someone/.opam/4.02.3/build/core_kernel.113.33.03/_build/src/std.cmt"}
{"time":304,"level":"info","section":"locate","title":null,"content":"Std.In_channel.fold_lines not in current file..."}
```

I have read the following: https://github.com/the-lambda-church/merlin/issues/234 and https://github.com/the-lambda-church/merlin/wiki/Letting-merlin-locate-go-to-stuff-in-.opam.

When trying locate `In_channel.fold_lines` I get the following error: `In_channel.fold_lines was supposed to be in /home/someone/.opam/4.02.3/build/core_kernel.113.33.03/_build/src/std.cmt but could not be found`. Why is it only looking in `std.cmt`? Why wouldn't it try to look for `in_channel.cmt` which is located in `/home/someone/.opam/4.02.3/build/core_kernel.113.33.03/_build/src`.

Any and all help is greatly appreciated, thanks!

**Comment by trefis** [comment]
Could you try with a more recent version of merlin?

**Comment by petroav** [comment]
@trefis Thanks for the suggestion, that worked. Apologies for not thinking of it myself, I think I got overloaded with details as it's my first time using Merlin, OPAM and Vim plugins.

One more question: it seems that after upgrading to Merlin 2.5.1 the `FLG -debug locate:debug,/tmp/some_file` line no longer works. Looking at `ocamlmerlin --help` I can't seem to find an option that enables me to control logging. My question is: how can I enable debug logging if I run into problems in the future? Thanks!

**Comment by trefis** [comment]
Cool!

Just have the environment variable `MERLIN_LOG` set to some file path before starting merlin and you will get all the logs in there.

**Comment by petroav** [comment]
Would you mind if I edited the wiki with this information? It seems like other people are also looking to do this: https://github.com/the-lambda-church/merlin/issues/560.

**Comment by trefis** [comment]
Sure, thanks!

**Comment by let-def** [comment]
This is my fault, I removed some debugging options recently.
I will provide an alternative in some later versions, sorry for the inconvenience.
