### ISSUE TITLE
assertion failed (4.04, merlin dev repo, in parmatch.ml:615)

### ISSUE THREAD

**Issue by hannesm** [the-lambda-church/merlin#601]
I use merlin git-44cbfac2 and OCaml-4.04.0 from opam.  I hit the assertion failure in typing/parmatch.ml:615 with some of my source files -- but ocamlbuild is happy to compile them.

Any way I can easily provide more debug output here?  Or is this a known problem?

**Comment by hannesm** [comment]
navigation commands (jump to definition) still work; when I want to jump to error, I get another assertion failed in typing/env.ml:1156.

**Comment by let-def** [comment]
Thanks for reporting, should be fixed now.

**Comment by hannesm** [comment]
thank you, will test tomorrow (once I'm back at my 4.04 computer) and report back

**Comment by hannesm** [comment]
upgraded, and turns out it works great now.  thanks!
