### ISSUE TITLE
Inline records are not (?) supported by Merlin

### ISSUE THREAD

**Issue by matej-kosik** [the-lambda-church/merlin#603]
I am not sure if Merlin is supposed to support constructions available in Ocaml 4.03.0, but when I use them in my program, e.g.:
```Ocaml
type foo = Bar of {baz : unit}
exception Foo of {bar : unit}
```
Merlin (2.5.1) can't yet cope with them. It claims that there are syntax-errors.

**Comment by let-def** [comment]
This code works well with my build of Merlin 2.5.1.
Could you check that the right binary is used? And eventually give more information (OS, editor version, ...).

**Comment by matej-kosik** [comment]
Oh. I've retried, this time also replacing the old `~/.emacs` configuration for the new one (displayed during the installation) and now all works.

Sorry for the noise.

There is no problem. I am closing this.
