### ISSUE TITLE
pervasives.cmi is not a compiled interface for this version of OCaml

### ISSUE THREAD

**Issue by tempodox** [the-lambda-church/merlin#604]
After doing `opam switch '4.04.0+flambda'`, I get the error,
`merlin.Error: {u'message': u'Error: ~/.opam/4.04.0+flambda/lib/ocaml/pervasives.cmi is not a compiled interface for this version of OCaml. It seems to be for a newer version of OCaml.', u'valid': True, u'type': u'type', u'sub': []}`
in vim when opening a source. This happens in a newly spawned shell, so the environment is updated after `opam switch`.

This error did not occur with `4.03.0+flambda`.

I must deactivate merlin completely, since it happens each time I open a source file.

**Comment by dbuenzli** [comment]
The cause is certainly that you are using a merlin for 4.03 against 4.04 code. You should install merlin in the 4.04 switch (you might need to do a `opam pin add merlin --dev-repo` in order to do so I'm not sure merlin support for 4.04 was released yet).

**Comment by tempodox** [comment]
I had merlin freshly installed in the new switch. Before `opam pin add merlin --dev-repo`:

`$ ocamlmerlin -version
The Merlin toolkit version 2.5.1, for Ocaml 4.04.0`

However, after `opam pin`, the error no longer occurs. `opam list` reports merlin at version 2.5.2 now. As far as I'm concerned, the issue is resolved.

Thank you very much!
