### ISSUE TITLE
Failed to compile in windows (MSVC) due to #include <unistd.h>

### ISSUE THREAD

**Issue by modlfo** [the-lambda-church/merlin#605]
I'm getting a compilation error in windows (using Visual Studio) in the file `merlin/src/platform/fs_case.c` because it includes `#include <unistd.h>` which is unix only.

I think this can be easily fixed by including that file for OSX and Linux only.

**Comment by let-def** [comment]
If you confirm the fix works, I will close the issue and release a new minor version.

**Comment by modlfo** [comment]
Hi! I tested the change and compiles successfully on windows.

Thanks.
