### ISSUE TITLE
Load externa libraries by specifying a path

### ISSUE THREAD

**Issue by Saroupille** [the-lambda-church/merlin#608]
I want to load an external library (a cmxa file) that is in a specific directory. What should I write in the .merlin file ?

I have try to do this but it does not work : 
`FLG -I "~/Git/project/_build"`

Thanks !

**Comment by let-def** [comment]
A cmxa contains object and linking information but no typing information. They are useful for producing executable but not for Merlin. You need to provide `*.cmi` and, optionally, `*.cmt(i)` files for Merlin to work.

The second problem is that merlin cannot expand `~/` in paths (though that could be a reasonable feature request). The correct specification would be:
```
B /home/.../Git/project/_build
```
where `/home/.../` is your `$HOME` directory (in macOS, it starts with `/Users/.../`).
